In [21]:
'''
Módulo 2 : Estadística y Visualización de Datos
Sesión : 01
Fecha : 25/10/2025
Actualización : 25/04/2026
'''
print("Módulo 2 : Estadística y Visualización de Datos")

Módulo 2 : Estadística y Visualización de Datos


- Documentación Numpy : https://numpy.org/doc/stable/reference/index.html#reference

## 1. Trabajando con listados

Objetivo: comparar el uso de listas de Python con arreglos de NumPy para entender ventajas de vectorizacion y metadatos (`dtype`, `shape`, `ndim`).

In [ ]:
import numpy as np

# Creando un array a partir de una lista
nro_list= [1, 2, 3, 4, 5]
nro_array = np.array(nro_list)

print("Lista type :", type(nro_list))
print("Array type :", type(nro_array))

# Creando un array directamente
nro_array = np.array([1, 2, 3, 4, 5])


Lista type : <class 'list'>
Array type : <class 'numpy.ndarray'>


In [18]:
import numpy as np

nros = [ x for x in range(5000)]
# print(nros)

In [19]:
# Creando un array a partir de una lista
np_nros = np.array(nros)
print(np_nros)

[   0    1    2 ... 4997 4998 4999]


In [ ]:
print("np_nros.dtype :", np_nros.dtype)
print("np_nros.ndim :", np_nros.ndim)
print("np_nros.size :", np_nros.size)
print("np_nros.shape :", np_nros.shape)
print("np_nros.itemsize :", np_nros.itemsize)
print("np_nros.data :", np_nros.data)


np_nros.dtype : int64
np_nros.ndim : 1
np_nros.size : 5000
np_nros.shape : (5000,)
np_nros.itemsize : 8
np_nros.data : <memory at 0x108c60e80>


## Ejercicio

-  Crear un arreglo numpy con los numeros 3,6,9, ...., 99

In [23]:
nros = [ 3*x for x in range(1,34)]
np_nros = np.array(nros)

In [24]:
import numpy as np

Ejercicio = [ x for x in range(3,100)]
np_nros = np.array(Ejercicio)
print(np_nros)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]


In [25]:
arreglo = np.arange(3, 100, 3)
print(arreglo)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [26]:
import numpy as np

nros = [x for x in range(3, 100, 3)] 
np_nros = np.array(nros) 

print(np_nros)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [ ]:
nros = [ x for x in range(3,100,3) ]
nro_array = np.array(nros)
print(nros)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96]


## 2. Trabajando con arreglos

Objetivo: crear arreglos 2D y revisar atributos clave para interpretar su estructura.

In [31]:
nros = [
        [ x for x in range(10)],
        [ y for y in range(10)],
        [ z for z in range(10)]
    ]
print(nros)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]


In [33]:
np_nros = np.array(nros)
np_nros

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
print("np_nros.dtype :", np_nros.dtype)
print("np_nros.ndim :", np_nros.ndim)
print("np_nros.size :", np_nros.size)
print("np_nros.shape :", np_nros.shape)
print("np_nros.itemsize :", np_nros.itemsize)
print("np_nros.data :", np_nros.data)

np_nros.dtype : int64
np_nros.ndim : 2
np_nros.size : 30
np_nros.shape : (3, 10)
np_nros.itemsize : 8
np_nros.data : <memory at 0x10846a670>


### Ejercicio 1

Crea un arreglo de NumPy con 3 filas:
- Fila 1: los 10 primeros números pares.
- Fila 2: los 10 primeros números impares.
- Fila 3: secuencia 10, 30, 50, ..., 110.

Pista: puedes usar `np.arange(inicio, fin, paso)` y luego combinar las secuencias en una sola matriz.

In [ ]:
# TO DO
# 1) Crea tres arreglos 1D segun el enunciado.
# 2) Unelos en una matriz de 3 filas.
# 3) Verifica la forma esperada con .shape.

In [42]:
nros = [
    [ x for x in range(0,12,2)],
    [ y for y in range(1,13,2)],
    [ z for z in range(10,130,20)]
]
print(nros)

[[0, 2, 4, 6, 8, 10], [1, 3, 5, 7, 9, 11], [10, 30, 50, 70, 90, 110]]


In [41]:
nros = [
    [ x for x in range(0,20,2)],
    [ y for y in range(1,21,2)],
    [ z for z in range(10,110,10)]
]
print(nros)
np_nros = np.array(nros)
print(np_nros)

[[0, 2, 4, 6, 8, 10, 12, 14, 16, 18], [1, 3, 5, 7, 9, 11, 13, 15, 17, 19], [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]]
[[  0   2   4   6   8  10  12  14  16  18]
 [  1   3   5   7   9  11  13  15  17  19]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [37]:
import numpy as np

fila1 = [2*x for x in range(6)]        # 0,2,4,6,8,10
fila2 = [2*x + 1 for x in range(6)]    # 1,3,5,7,9,11
fila3 = [20*x + 10 for x in range(6)]  # 10,30,50,70,90,110

np_nros = np.array([fila1, fila2, fila3])

print(np_nros)

[[  0   2   4   6   8  10]
 [  1   3   5   7   9  11]
 [ 10  30  50  70  90 110]]


In [ ]:
import numpy as np

fila1 = np.arange(0, 11, 2) 
fila2 = np.arange(1, 12, 2)
fila3 = np.arange(10, 111, 20)
matriz = np.array([fila1, fila2, fila3])

print("Matriz resultante:")
print(matriz)

Matriz resultante:
[[  0   2   4   6   8  10]
 [  1   3   5   7   9  11]
 [ 10  30  50  70  90 110]]


## 3. Creacion de arreglos NumPy

Objetivo: practicar constructores frecuentes (`zeros`, `ones`, `arange`) para generar arreglos de forma rapida.

In [ ]:
np_z = np.zeros((3, 4))  # Arreglo de ceros de 3 filas y 4 columnas    
np_z

In [ ]:
np_o = np.ones((2, 5))  # Arreglo de unos de 2 filas y 5 columnas    
np_o

In [ ]:
np_nros = np.arange(30, 51)  # Arreglo con valores desde 10 hasta 50
np_nros

## 4. Operaciones basicas

Objetivo: aplicar operaciones aritmeticas vectorizadas y comparar con listas tradicionales.

In [ ]:
# Como sumamos a una lista un valor escalar?
arr1 = range(4)
print("arr1 :", arr1)
#print("arr1 + 5 :", arr1 + 5) # Esto generará un error
print("arr1 + 5 :", [x + 5 for x in arr1])  # Suma 5 a cada elemento usando comprensión de listas

In [ ]:
# SUMA Y MULTIPLICACION CON NUMPY
np_arr1 = np.arange(4)
print("np_arr1 :", np_arr1)
print("Suma 5 a cada elemento de np_arr1 :",np_arr1  + 5 )  # Suma 5 a cada elemento
print("Multiplica por 5 a cada elemento de np_arr1 :",np_arr1  * 5 )  # Multiplicar por 5 a cada elemento

In [ ]:
# RESTA Y DIVISION CON NUMPY
np_arr1 = np.arange(4,8)
print("np_arr1 :", np_arr1)
print("Resta 5 a cada elemento de np_arr1 :",np_arr1  - 5 )  # Resta 5 a cada elemento
print("Divide 5 a cada elemento de np_arr1 :",np_arr1  / 5 )  # Divide 5 a cada elemento

### Ejercicio 2

Crea un arreglo de NumPy con la secuencia 10, 30, 50, ..., 130. Luego aplica en cadena estas operaciones:
- Divide todos los elementos entre 10.
- Resta 3 al resultado anterior.
- Suma 1 al resultado anterior.
- Multiplica por -1 el resultado final y muestralo.

Pista: usa una variable intermedia por cada paso para revisar tu proceso.

In [ ]:
# TO DO
# 1) Genera la secuencia con arange (ajustando el paso).
# 2) Aplica cada transformacion en orden.
# 3) Imprime el resultado final.

In [ ]:
# Operaciones entre arreglos
np_arr1 = np.arange(4)      
np_arr2 = np.arange(4,8)

print("np_arr1 :", np_arr1)
print("np_arr2 :", np_arr2)    
print("Suma de np_arr1 + np_arr2 :", np_arr1 + np_arr2)
print("Resta de np_arr1 - np_arr2 :", np_arr1 - np_arr2)
print("Multiplicacion de np_arr1 * np_arr2 :", np_arr1 * np_arr2)
print("Division de np_arr1 / np_arr2 :", np_arr1 / np_arr2)


In [ ]:
(np_arr1 / np_arr2)*np_arr2

### Ejercicio 3

Se tienen los arreglos:
- [0, 1, 0]
- [1, 0, 0]
- [0, 0, 1]

Calcula:
- La suma entre arreglos.
- El producto entre arreglos.

Pista: define cada arreglo como `np.array(...)` y prueba operaciones elemento a elemento.

In [ ]:
# TO DO
# 1) Crea los tres arreglos.
# 2) Realiza la suma solicitada.
# 3) Realiza el producto solicitado.
# 4) Muestra resultados con print().

## 5. Producto de matrices

Objetivo: interpretar el producto punto y su uso en operaciones matriciales.

<img src="imagenes/producto_punto.jpg" width="400" />

In [ ]:
a_arr = np.arange(4)      
b_arr = np.arange(4,8)

print("a_arr :", a_arr)
print("b_arr :", b_arr)
print(sum(a_arr * b_arr))
print(np.dot(a_arr, b_arr))  # Producto punto de a_arr y b_arr
print(np.dot(b_arr, a_arr))  # Producto punto de b_arr y a_arr


In [ ]:
a_arr = np.array([[1, 2], [3, 4]])
b_arr = np.array([[5, 6], [7, 8]])      

print("a_arr :\n", a_arr)
print("b_arr :\n", b_arr)

c_arr = a_arr.dot(b_arr)
print("Producto de matrices a_arr . b_arr :\n", c_arr)  

c_arr = np.dot(a_arr,b_arr)
print("Producto de matrices a_arr . b_arr :\n", c_arr)  


In [ ]:
# Cambiar la forma de un arreglo
np_arr = np.arange(12)  # Arreglo con valores del 0 al 11
print("Arreglo original:")
print(np_arr)
np_arr_reshaped = np_arr.reshape((3, 4))  # Cambiar la forma a 3 filas y 4 columnas
print("Arreglo con nueva forma (3x4):")
print(np_arr_reshaped)

### Ejercicio 4

Dados los vectores:
- A = [3, 4]
- B = [2, 5]

Calcula:
- El producto punto `A · B`.
- Las magnitudes `|A|` y `|B|`.

Pista: puedes usar `np.dot` y `np.linalg.norm`.

In [ ]:
# TO DO
# 1) Define los vectores A y B como np.array.
# 2) Calcula el producto punto.
# 3) Calcula las magnitudes de ambos vectores.
# 4) Muestra los resultados.

## 6. Funciones utilitarias

Objetivo: usar funciones de agregacion y estadistica descriptiva con NumPy.

In [ ]:
a_arr = np.arange(4,8)
print("a_arr :", a_arr)

# Elevar a una potencia cada elemento
print("a_arr elevado al cubo :", np.power(a_arr, 3))

# Sumar todos los elementos del arreglo
print("Suma de todos los elementos de a_arr :", np.sum(a_arr))

# Obtener el valor minimo de todos los elementos
print("Valor minimo de a_arr :", np.min(a_arr))

# Obtener el valor maximo de todos los elementos
print("Valor maximo de a_arr :", np.max(a_arr)) 

# Calcular la media de los elementos
print("Media de los elementos de a_arr :", np.mean(a_arr))

# Calcular la desviacion estandar de los elementos
print("Desviacion estandar de los elementos de a_arr :", np.std(a_arr))

# Calcular la varianza de los elementos
print("Varianza de los elementos de a_arr :", np.var(a_arr))    

# Calcular la raiz cuadrada de cada elemento
print("Raiz cuadrada de cada elemento de a_arr :", np.sqrt(a_arr))  


### Ejercicio 6

Dadas las notas de 2 estudiantes en 5 cursos:
- estudiante_A = np.array([18, 14, 20, 10, 15])
- estudiante_B = np.array([17, 16, 17, 14, 18])

Construye una tabla comparativa con:
- Nota promedio
- Nota minima
- Nota maxima

Pista: usa `np.mean`, `np.min` y `np.max`.

In [ ]:
# TO DO
# 1) Define ambos arreglos de notas.
# 2) Calcula promedio, minima y maxima para cada estudiante.
# 3) Presenta los resultados en una estructura comparativa.

## 7. Iteraciones por columnas y filas

Objetivo: practicar agregaciones por ejes (`axis=0` y `axis=1`) en matrices.

In [ ]:
a_arr = np.arange(0,12).reshape((3,4))
print("a_arr :\n", a_arr)

# Sumas

# Procesar por columnas
col_proc = np.apply_along_axis(np.sum, axis=0, arr=a_arr)
print("Suma por columnas :", col_proc)

# Procesar por filas
filas_proc = np.apply_along_axis(np.sum, axis=1, arr=a_arr)
print("Suma por filas :", filas_proc)

# Promedios

# Procesar por columnas
col_proc = np.apply_along_axis(np.mean, axis=0, arr=a_arr)
print("Promedio por columnas :", col_proc)

# Procesar por filas
filas_proc = np.apply_along_axis(np.mean, axis=1, arr=a_arr)
print("Promedio por filas :", filas_proc)


In [ ]:
def potencia(x):
    return x ** 2

a_arr = np.arange(0,12).reshape((3,4))
print("a_arr :\n", a_arr)


b_arr =  np.apply_along_axis(potencia, axis=1, arr=a_arr)
print("b_arr :\n", b_arr)

### Ejercicio 7

Dado el PBI de Chile, Peru y Colombia entre 2020 y 2026, calcula:
- El promedio del PBI de los 3 paises por año.
- El promedio historico del PBI de cada pais (2020-2026).

Datos:
- Peru -> 209,984 229,832 248,204 271,780 294,675 318,480 326,608
- Chile -> 254,060 315,411 301,270 335,627 330,210 347,174 363,299
- Colombia -> 270,348 318,525 345,632 366,292 418,818 438,121 462,251

Crea arreglos para cada pais (sin incluir los nombres):
- `peru = np.array([...])`
- `chile = np.array([...])`
- `colombia = np.array([...])`

Pista: apila los arreglos en una sola matriz y usa operaciones por eje.

In [ ]:
# TO DO
# 1) Crea los arreglos peru, chile y colombia.
# 2) Construye una matriz con los tres paises.
# 3) Calcula promedios por año y por pais usando axis.
# 4) Muestra resultados con etiquetas claras.

## 8. Condiciones y expresiones booleanas

Objetivo: filtrar datos con condiciones y mascaras booleanas.

In [ ]:
a_arr = np.arange(0,12).reshape((3,4))
print("a_arr :\n", a_arr)

# Condiciones y expresio
print(a_arr > 5)

In [ ]:
a_arr[a_arr > 5]

### Ejercicio 8

Dadas las notas de 2 estudiantes:
- `estudiante_A = np.array([18, 14, 20, 10, 15])`
- `estudiante_B = np.array([17, 16, 17, 14, 18])`

Calcula:
- El promedio general de todas las notas.
- Las notas que son mayores a ese promedio.

Pista: combina ambos arreglos y utiliza una mascara booleana para filtrar.

In [ ]:
# TO DO
# 1) Define ambos arreglos de notas.
# 2) Combina las notas en un solo arreglo.
# 3) Calcula el promedio general.
# 4) Filtra las notas mayores al promedio.

## 9. Cambio de dimension de un arreglo

Objetivo: transformar la forma de un arreglo sin alterar sus datos.

In [ ]:
# Creacion de un arreglo aleatorio, de 3 x4 
a_arr = np.random.random((3,4))
print("a_arr :\n", a_arr)

# Cambio de dimension de un arreglo
print(a_arr.ravel())

## 10. Transpuesta de matrices

Objetivo: comprender el intercambio entre filas y columnas usando `.T` o `np.transpose`.

In [ ]:
# Creacion de un arreglo aleatorio, de 1x2 
a_arr = np.random.random((1,2))
print("a_arr :\n", a_arr)

# Generacion de matriz transpuesta
print("Matriz transpuesta de a_arr :\n", a_arr.T)
print("Matriz transpuesta de a_arr :\n", np.transpose(a_arr))


### Ejercicio 10

Crea una matriz `2x3` con numeros enteros aleatorios entre 0 y 100 y calcula su transpuesta.

Pista: puedes usar `np.random.randint` y luego `.T`.

In [ ]:
# TO DO
# 1) Genera una matriz aleatoria de forma (2, 3).
# 2) Calcula su transpuesta.
# 3) Imprime ambas matrices para comparar dimensiones.

## 11. Union de matrices

Objetivo: combinar matrices por filas y columnas usando funciones de concatenacion.

In [ ]:
a_arr = np.ones((3,3))
print("a_arr :\n", a_arr)

b_arr = np.zeros((3,3))
print("b_arr :\n", b_arr)

In [ ]:
np.vstack((a_arr, b_arr))

In [ ]:
np.hstack((a_arr, b_arr))

In [ ]:
a_arr = np.array([10, 20, 30])
b_arr = np.array([40, 50, 60])
c_arr = np.array([70, 80, 90])

np.concatenate((a_arr, b_arr, c_arr))

In [ ]:
np.vstack((a_arr, b_arr, c_arr)) #  Use `np.vstack` directly

In [ ]:
np.column_stack((a_arr, b_arr, c_arr)) # Use `np.hstack` directly

### Ejercicio 11

Construye el siguiente arreglo:

$$
\begin{bmatrix}
1 & 2 & 3 & 4 & 1 & 1 & 1 \\
5 & 6 & 7 & 8 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 2 & 4 & 6 \\
0 & 0 & 0 & 0 & 8 & 10 & 12 \\
1 & 1 & 1 & 1 & -1 & -1 & -1 \\
1 & 1 & 1 & 1 & -1 & -1 & -1
\end{bmatrix}
$$

Pista: crea bloques por separado y unelos con operaciones de concatenacion.

In [ ]:
# TO DO
# 1) Crea submatrices (bloques) con los valores solicitados.
# 2) Une los bloques por filas/columnas para formar la matriz final.
# 3) Verifica la forma final con .shape.

## 12.- Referencia a Objetos

In [ ]:
a_arr = np.array([1, 2, 3, 4])
print("a_arr :", a_arr)

In [ ]:
ref_a_arr = a_arr
print("ref_a_arr :", ref_a_arr)

In [ ]:
ref_a_arr[0] = 10
print("Después de modificar ref_a_arr[0] a 10:")
print("a_arr :", a_arr)
print("ref_a_arr :", ref_a_arr)

## 13.- Vista de Objetos

In [ ]:
a_arr = np.array([10, 20, 30, 40])
print("a_arr :", a_arr)

In [ ]:
vista_a_arr = a_arr[0:4]
print("vista_a_arr :", vista_a_arr)

In [ ]:
vista_a_arr[0] = 1000
print("Después de modificar vista_a_arr[0] a 1000:")
print("a_arr :", a_arr)
print("vista_a_arr :", vista_a_arr)

## 14.- Copia de un objeto

In [ ]:
a_arr = np.array([10, 20, 30, 40])
print("a_arr :", a_arr)

In [ ]:
vista_a_arr = a_arr.copy()
print("vista_a_arr :", vista_a_arr)

In [ ]:
vista_a_arr[0] = 1000
print("Después de modificar vista_a_arr[0] a 1000:")
print("a_arr :", a_arr)
print("vista_a_arr :", vista_a_arr)

## 15.- Lectura de archivos

In [ ]:
import numpy as np

# Lectura de datos desde un archivo de texto
data = np.loadtxt('entregas.txt', skiprows=1)
print(data)

In [ ]:
# Lectura de datos desde un archivo de texto, seleccionando columnas específicas
data = np.loadtxt('entregas.txt', skiprows=1, usecols=(0,1))
print(data)

In [ ]:
## Lectura de archivo CSV con numpy
data = np.genfromtxt('entregas.csv', delimiter=';', skip_header=1)
print(data)

In [ ]:
# Cargar archivo CSV con grenfromtxt
data = np.genfromtxt('dataset/panamericanos/medallero_Panamericanos_Lima2019.csv', delimiter=',', names=True, dtype=None)
print(data)

In [ ]:
# Cargar archivo CSV con grenfromtxt
data = np.genfromtxt('dataset/panamericanos/medallero_Panamericanos_Lima2019.csv', delimiter=',', names=True, dtype=None, encoding='utf-8')
print(data)

In [ ]:
data = np.fromfile('binario.bin', dtype=np.float64)
print(data)

In [ ]:
data = np.fromfile('binario.bin', dtype=np.float64, count=3)
print(data)

## 16. Escritura de archivos

Objetivo: guardar resultados procesados en archivos para reutilizarlos en otros flujos de trabajo.

In [ ]:

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.savetxt('salida.txt', data, fmt='%d', delimiter=',')


In [ ]:
data = np.array([10, 20, 30])
np.save("data.npy", data)


data_loaded = np.load("data.npy")
print(data_loaded)
