In [39]:
'''
Modulo 2 : Estadistica y Visualizacion de Datos
Sesion : 01
Fecha : 25/10/2025
'''
print("Modulo 2 : Estadistica y Visualizacion de Datos")

Modulo 2 : Estadistica y Visualizacion de Datos


### 1.- Trabajando con listados

In [40]:
import numpy as np

nros = [ x for x in range(30)]
print(nros)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


In [41]:
np_nros = np.array(nros)
print(np_nros)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [42]:
print("np_nros.dtype :", np_nros.dtype)
print("np_nros.ndim :", np_nros.ndim)
print("np_nros.size :", np_nros.size)
print("np_nros.shape :", np_nros.shape)
print("np_nros.itemsize :", np_nros.itemsize)
print("np_nros.data :", np_nros.data)

np_nros.dtype : int64
np_nros.ndim : 1
np_nros.size : 30
np_nros.shape : (30,)
np_nros.itemsize : 8
np_nros.data : <memory at 0x107a32080>


### 2.- Trabajando con Arrays

In [43]:
nros = [
        [ x for x in range(10)],
        [ y for y in range(10)],
        [ z for z in range(10)]
    ]
#print(nros)
np_nros = np.array(nros)
print(np_nros)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [44]:
print("np_nros.dtype :", np_nros.dtype)
print("np_nros.ndim :", np_nros.ndim)
print("np_nros.size :", np_nros.size)
print("np_nros.shape :", np_nros.shape)
print("np_nros.itemsize :", np_nros.itemsize)
print("np_nros.data :", np_nros.data)

np_nros.dtype : int64
np_nros.ndim : 2
np_nros.size : 30
np_nros.shape : (3, 10)
np_nros.itemsize : 8
np_nros.data : <memory at 0x107a7cd40>


#### Ejercicio 1 : Crear un arreglo numpy que tenga 3 filas, 
- La 1ra fila tiene los numeros de 0,2,....,10 
- La 2da fila tiene los numeros : 1,3,5,...,11
- La 3ra fila tiene los numeros : 10, 30, 50 , ...., 110.

In [50]:
import numpy as np

fila1 = range(0, 11, 2)  
fila2 = range(1, 12, 2)  
fila3 = range(10, 111, 20)  
arreglo = np.array([fila1, fila2, fila3])
print("Arreglo resultante:")
print(arreglo)

Arreglo resultante:
[[  0   2   4   6   8  10]
 [  1   3   5   7   9  11]
 [ 10  30  50  70  90 110]]


### 2.- Creación de Arrays Numpy

In [47]:
np_z = np.zeros((3, 4))  # Arreglo de ceros de 3 filas y 4 columnas    
np_z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np_o = np.ones((2, 5))  # Arreglo de unos de 2 filas y 5 columnas    
np_o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
np_nros = np.arange(30, 51)  # Arreglo con valores desde 10 hasta 50
np_nros

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50])

### 3.- Operaciones Básicas

In [ ]:
# Como sumamos a una lista un valor escalar?
arr1 = range(4)
print("arr1 :", arr1)
#print("arr1 + 5 :", arr1 + 5) # Esto generará un error
print("arr1 + 5 :", [x + 5 for x in arr1])  # Suma 5 a cada elemento usando comprensión de listas

arr1 : range(0, 4)
arr1 + 5 : [5, 6, 7, 8]


In [67]:
# SUMA Y MULTIPLICACION CON NUMPY
np_arr1 = np.arange(4)
print("np_arr1 :", np_arr1)
print("Suma 5 a cada elemento de np_arr1 :",np_arr1  + 5 )  # Suma 5 a cada elemento
print("Multiplica por 5 a cada elemento de np_arr1 :",np_arr1  * 5 )  # Multiplicar por 5 a cada elemento

np_arr1 : [0 1 2 3]
Suma 5 a cada elemento de np_arr1 : [5 6 7 8]
Multiplica por 5 a cada elemento de np_arr1 : [ 0  5 10 15]


In [68]:
# RESTA Y DIVISION CON NUMPY
np_arr1 = np.arange(4,8)
print("np_arr1 :", np_arr1)
print("Resta 5 a cada elemento de np_arr1 :",np_arr1  - 5 )  # Resta 5 a cada elemento
print("Divide 5 a cada elemento de np_arr1 :",np_arr1  / 5 )  # Divide 5 a cada elemento

np_arr1 : [4 5 6 7]
Resta 5 a cada elemento de np_arr1 : [-1  0  1  2]
Divide 5 a cada elemento de np_arr1 : [0.8 1.  1.2 1.4]


### Ejercicio 2 : 
Crear un arreglo numpy con los números 10,30,50,70,...,130 luego realizar las siguiente operaciones
- Dividir entre 10 a todos los elementos
- Restar 3 al resultado anterior
- Sumar 1 a resultado anterior
- Mutiplicar por -1 al resultado anterior y mostrarlo

In [ ]:
np_arr_original = np.arange(10,150,20)

np_arr2 = np_arr_original.copy()  
print(np_arr2)

np_arr2 = np_arr2 / 10
print("np_arr2 suma : ", np_arr2)

np_arr2 = np_arr2 -3
print("np_arr2 menos 3 : ", np_arr2)

print("np_arr_original : ", np_arr_original)

[ 10  30  50  70  90 110 130]
np_arr2 suma :  [ 1.  3.  5.  7.  9. 11. 13.]
np_arr2 menos 3 :  [-2.  0.  2.  4.  6.  8. 10.]
np_arr_original :  [ 10  30  50  70  90 110 130]


In [78]:
# Operaciones entre arreglos
np_arr1 = np.arange(4)      
np_arr2 = np.arange(4,8)

print("np_arr1 :", np_arr1)
print("np_arr2 :", np_arr2)    
print("Suma de np_arr1 + np_arr2 :", np_arr1 + np_arr2)
print("Resta de np_arr1 - np_arr2 :", np_arr1 - np_arr2)
print("Multiplicacion de np_arr1 * np_arr2 :", np_arr1 * np_arr2)
print("Division de np_arr1 / np_arr2 :", np_arr1 / np_arr2)


np_arr1 : [0 1 2 3]
np_arr2 : [4 5 6 7]
Suma de np_arr1 + np_arr2 : [ 4  6  8 10]
Resta de np_arr1 - np_arr2 : [-4 -4 -4 -4]
Multiplicacion de np_arr1 * np_arr2 : [ 0  5 12 21]
Division de np_arr1 / np_arr2 : [0.         0.2        0.33333333 0.42857143]


In [79]:
(np_arr1 / np_arr2)*np_arr2

array([0., 1., 2., 3.])

### Ejercicio 3 :
se tiene los siguiente arreglos
- [0,1,0]
- [1,0,0]
- [0,0,1]

Se pide calcular la suma y el producto de los arreglos

In [83]:
import numpy as np

array1 = np.array([0, 1, 0])
array2 = np.array([1, 0, 0])
array3 = np.array([0, 0, 1])

suma = array1 + array2 + array3
producto = array1*array2*array3

print("suma: ", suma)
print("producto: ", producto)

suma:  [1 1 1]
producto:  [0 0 0]


### 4.- Producto de matrices

<img src="imagenes/producto_punto.jpg" width="400" />

In [86]:
a_arr = np.arange(4)      
b_arr = np.arange(4,8)

print("a_arr :", a_arr)
print("b_arr :", b_arr)
print(sum(a_arr * b_arr))
print(np.dot(a_arr, b_arr))  # Producto punto de a_arr y b_arr
print(np.dot(b_arr, a_arr))  # Producto punto de b_arr y a_arr


a_arr : [0 1 2 3]
b_arr : [4 5 6 7]
38
38
38


In [88]:
a_arr = np.array([[1, 2], [3, 4]])
b_arr = np.array([[5, 6], [7, 8]])      

print("a_arr :\n", a_arr)
print("b_arr :\n", b_arr)

c_arr = a_arr.dot(b_arr)
print("Producto de matrices a_arr . b_arr :\n", c_arr)  

c_arr = np.dot(a_arr,b_arr)
print("Producto de matrices a_arr . b_arr :\n", c_arr)  


a_arr :
 [[1 2]
 [3 4]]
b_arr :
 [[5 6]
 [7 8]]
Producto de matrices a_arr . b_arr :
 [[19 22]
 [43 50]]
Producto de matrices a_arr . b_arr :
 [[19 22]
 [43 50]]


## Ejercicio 4
Dados los vectores:

- A = [3, 4]
- B = [2, 5]

Calcular:

- El producto punto A · B
- Las magnitudes |A| y |B|

In [90]:
# Cambiar la forma de un arreglo
np_arr = np.arange(12)  # Arreglo con valores del 0 al 11
print("Arreglo original:")
print(np_arr)
np_arr_reshaped = np_arr.reshape((3, 4))  # Cambiar la forma a 3 filas y 4 columnas
print("Arreglo con nueva forma (3x4):")
print(np_arr_reshaped)

Arreglo original:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Arreglo con nueva forma (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 5.- Funciones utilitarias 

In [93]:
a_arr = np.arange(4,8)
print("a_arr :", a_arr)

# Elevar a una potencia cada elemento
print("a_arr elevado al cubo :", np.power(a_arr, 3))

# Sumar todos los elementos del arreglo
print("Suma de todos los elementos de a_arr :", np.sum(a_arr))

# Obtener el valor minimo de todos los elementos
print("Valor minimo de a_arr :", np.min(a_arr))

# Obtener el valor maximo de todos los elementos
print("Valor maximo de a_arr :", np.max(a_arr)) 

# Calcular la media de los elementos
print("Media de los elementos de a_arr :", np.mean(a_arr))

# Calcular la desviacion estandar de los elementos
print("Desviacion estandar de los elementos de a_arr :", np.std(a_arr))

# Calcular la varianza de los elementos
print("Varianza de los elementos de a_arr :", np.var(a_arr))    

# Calcular la raiz cuadrada de cada elemento
print("Raiz cuadrada de cada elemento de a_arr :", np.sqrt(a_arr))  


a_arr : [4 5 6 7]
a_arr elevado al cubo : [ 64 125 216 343]
Suma de todos los elementos de a_arr : 22
Valor minimo de a_arr : 4
Valor maximo de a_arr : 7
Media de los elementos de a_arr : 5.5
Desviacion estandar de los elementos de a_arr : 1.118033988749895
Varianza de los elementos de a_arr : 1.25
Raiz cuadrada de cada elemento de a_arr : [2.         2.23606798 2.44948974 2.64575131]


## Ejercicio 6

Dada las notas de 2 estudiantes en 5 cursos

- estudiante_A = np.array([18, 14, 20, 10, 15])
- estudiante_B = np.array([17, 16, 17, 14, 18])

Calcular una tabla comparativa de la nota promedio , miníma y máxima de los estudiantes

