In [22]:
'''
Modulo 2 : Estadistica y Visualizacion de Datos
Sesion : 01
Fecha : 25/10/2025
'''
print("Modulo 2 : Estadistica y Visualizacion de Datos")

Modulo 2 : Estadistica y Visualizacion de Datos


### Trabajando con listados

In [23]:
import numpy as np

nros = [ x for x in range(30)]
print(nros)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


In [24]:
np_nros = np.array(nros)
print(np_nros)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [25]:
print("np_nros.dtype :", np_nros.dtype)
print("np_nros.ndim :", np_nros.ndim)
print("np_nros.size :", np_nros.size)
print("np_nros.shape :", np_nros.shape)
print("np_nros.itemsize :", np_nros.itemsize)
print("np_nros.data :", np_nros.data)

np_nros.dtype : int64
np_nros.ndim : 1
np_nros.size : 30
np_nros.shape : (30,)
np_nros.itemsize : 8
np_nros.data : <memory at 0x107a31b40>


### Trabajando con Arrays

In [28]:
nros = [
        [ x for x in range(10)],
        [ y for y in range(10)],
        [ z for z in range(10)]
    ]
#print(nros)
np_nros = np.array(nros)
print(np_nros)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [29]:
print("np_nros.dtype :", np_nros.dtype)
print("np_nros.ndim :", np_nros.ndim)
print("np_nros.size :", np_nros.size)
print("np_nros.shape :", np_nros.shape)
print("np_nros.itemsize :", np_nros.itemsize)
print("np_nros.data :", np_nros.data)

np_nros.dtype : int64
np_nros.ndim : 2
np_nros.size : 30
np_nros.shape : (3, 10)
np_nros.itemsize : 8
np_nros.data : <memory at 0x107a7cc70>
