
- Modulo 2 : Estadistica y Visualizacion de Datos
- Sesion : 02
- Fecha : 08/11/2025


In [4]:
import pandas as pd
import numpy as np

In [5]:
listado_docentes = {
    "0001": {
        "nombres": "Ana Maria",
        "apellidos": "Lopez Garcia",
        "edad": 34
    },
    "0002": {
        "nombres": "Juan Carlos",
        "apellidos": "Perez Soto",
        "edad": 45
        }
    }

print(listado_docentes["0002"])

{'nombres': 'Juan Carlos', 'apellidos': 'Perez Soto', 'edad': 45}


In [8]:
df = pd.DataFrame(listado_docentes)
print(df)

                   0001         0002
nombres       Ana Maria  Juan Carlos
apellidos  Lopez Garcia   Perez Soto
edad                 34           45


In [14]:
df[["0001"]]

0001
nombres       Ana Maria
apellidos  Lopez Garcia
edad                 34

In [15]:
df.head()

0001         0002
nombres       Ana Maria  Juan Carlos
apellidos  Lopez Garcia   Perez Soto
edad                 34           45

In [16]:
df["0003"] =  df["0002"]

In [18]:
df.head()

0001         0002         0003
nombres       Ana Maria  Juan Carlos  Juan Carlos
apellidos  Lopez Garcia   Perez Soto   Perez Soto
edad                 34           45           45

In [19]:
df["0004"] =  df["0003"] +df["0002"]

df.head()

0001         0002         0003                    0004
nombres       Ana Maria  Juan Carlos  Juan Carlos  Juan CarlosJuan Carlos
apellidos  Lopez Garcia   Perez Soto   Perez Soto    Perez SotoPerez Soto
edad                 34           45           45                      90

In [20]:
df.insert(1, "1111", df["0003"] )
df.head()

0001         1111         0002         0003  \
nombres       Ana Maria  Juan Carlos  Juan Carlos  Juan Carlos   
apellidos  Lopez Garcia   Perez Soto   Perez Soto   Perez Soto   
edad                 34           45           45           45   

                             0004  
nombres    Juan CarlosJuan Carlos  
apellidos    Perez SotoPerez Soto  
edad                           90

In [23]:
df = df.assign( nuevo = ["Jose","Rubio",34])

In [24]:
df.head()

0001         1111         0002         0003  \
nombres       Ana Maria  Juan Carlos  Juan Carlos  Juan Carlos   
apellidos  Lopez Garcia   Perez Soto   Perez Soto   Perez Soto   
edad                 34           45           45           45   

                             0004  nuevo  
nombres    Juan CarlosJuan Carlos   Jose  
apellidos    Perez SotoPerez Soto  Rubio  
edad                           90     34

## Series con Pandas

In [26]:
nro_list = [10,20,40,60,80]
serie_pd = pd.Series(nro_list)
print(serie_pd)

0    10
1    20
2    40
3    60
4    80
dtype: int64


In [28]:
mi_listado = [x for x in range(2,101,2)]
serie_pares = pd.Series(mi_listado)
serie_pares

0       2
1       4
2       6
3       8
4      10
5      12
6      14
7      16
8      18
9      20
10     22
11     24
12     26
13     28
14     30
15     32
16     34
17     36
18     38
19     40
20     42
21     44
22     46
23     48
24     50
25     52
26     54
27     56
28     58
29     60
30     62
31     64
32     66
33     68
34     70
35     72
36     74
37     76
38     78
39     80
40     82
41     84
42     86
43     88
44     90
45     92
46     94
47     96
48     98
49    100
dtype: int64

In [29]:
mi_listado = range(2,101,2)
serie_pares = pd.Series(mi_listado)
serie_pares

0       2
1       4
2       6
3       8
4      10
5      12
6      14
7      16
8      18
9      20
10     22
11     24
12     26
13     28
14     30
15     32
16     34
17     36
18     38
19     40
20     42
21     44
22     46
23     48
24     50
25     52
26     54
27     56
28     58
29     60
30     62
31     64
32     66
33     68
34     70
35     72
36     74
37     76
38     78
39     80
40     82
41     84
42     86
43     88
44     90
45     92
46     94
47     96
48     98
49    100
dtype: int64

## Convertir ndarray a serie data frame

In [30]:
nro_list = np.array([10,20,40,60,80])
serie_pd = pd.Series(nro_list)
print(serie_pd)

0    10
1    20
2    40
3    60
4    80
dtype: int64


In [31]:
mi_listado = np.arange(2,101,2)
serie_pares = pd.Series(mi_listado)
serie_pares

0       2
1       4
2       6
3       8
4      10
5      12
6      14
7      16
8      18
9      20
10     22
11     24
12     26
13     28
14     30
15     32
16     34
17     36
18     38
19     40
20     42
21     44
22     46
23     48
24     50
25     52
26     54
27     56
28     58
29     60
30     62
31     64
32     66
33     68
34     70
35     72
36     74
37     76
38     78
39     80
40     82
41     84
42     86
43     88
44     90
45     92
46     94
47     96
48     98
49    100
dtype: int64

# Estadísticos descriptivos con statsmodels

In [34]:
import statsmodels.api as sm

a_matrix = np.arange(0,16)
a_matrix  

desc = sm.stats.DescrStatsW(a_matrix)

print(desc.mean)
print(desc.std)
print(desc.var)
print(desc.cov)
print(desc.quantile([0.25,0.5,0.75]))     


7.5
4.6097722286464435
21.25
21.25
p
0.25     3
0.50     7
0.75    11
dtype: int64


# Estadísticos descriptivos con scipy

In [35]:
import scipy.stats as stats

a_matrix = np.arange(0,16)
a_matrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
print("Minimo:", stats.tmin(a_matrix))
print("Maximo:", stats.tmax(a_matrix))
print("Media:", stats.tmean(a_matrix))
print("Varianza:", stats.tvar(a_matrix))
print("Desviacion Estandar:", stats.tstd(a_matrix)) 
print("Percentil 25:", stats.scoreatpercentile(a_matrix,25))
print("Percentil 50:", stats.scoreatpercentile(a_matrix,50))
print("Percentil 75:", stats.scoreatpercentile(a_matrix,75))
print("Rango intercuartilico:", stats.iqr(a_matrix))
print("Moda:", stats.mode(a_matrix))



Minimo: 0
Maximo: 15
Media: 7.5
Varianza: 22.666666666666668
Desviacion Estandar: 4.760952285695233
Percentil 25: 3.75
Percentil 50: 7.5
Percentil 75: 11.25
Rango intercuartilico: 7.5
Moda: ModeResult(mode=np.int64(0), count=np.int64(1))


# Estadísticos descriptivos para ndarray

In [44]:
a_matrix = np.arange(0,16).reshape(4,4)
a_matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
print("Suma:", a_matrix.sum())
print("Media:", a_matrix.mean())
print("Minimo:", a_matrix.min())
print("Maximo:", a_matrix.max())
print("Varianza:", a_matrix.var())
print("Desviacion Estandar:", a_matrix.std()) 


Suma: 120
Media: 7.5
Minimo: 0
Maximo: 15
Varianza: 21.25
Desviacion Estandar: 4.6097722286464435


In [50]:
AXIS = 1 # 0 Columna , 1 : Fila
print(a_matrix)
print("Suma:", a_matrix.sum(AXIS))
print("Media:", a_matrix.mean(AXIS))
print("Minimo:", a_matrix.min(AXIS))
print("Maximo:", a_matrix.max(AXIS))
print("Varianza:", a_matrix.var(AXIS))
print("Desviacion Estandar:", a_matrix.std(AXIS)) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Suma: [ 6 22 38 54]
Media: [ 1.5  5.5  9.5 13.5]
Minimo: [ 0  4  8 12]
Maximo: [ 3  7 11 15]
Varianza: [1.25 1.25 1.25 1.25]
Desviacion Estandar: [1.11803399 1.11803399 1.11803399 1.11803399]


# Estadísticos descriptivos con numpy

In [52]:
a_matrix = np.arange(0,16).reshape(4,4)
a_matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
print("Sum:", np.sum(a_matrix))
print("Min:", np.min(a_matrix))
print("Max:", np.max(a_matrix))
print("Media:", np.mean(a_matrix))
print("Mediana:", np.median(a_matrix))
print("Moda:", stats.mode(a_matrix))
print("Varianza:", np.var(a_matrix))
print("Desviacion Estandar:", np.std(a_matrix))
print("Percentil 25:", np.percentile(a_matrix,25))
print("Percentil 50:", np.percentile(a_matrix,50))
print("Percentil 75:", np.percentile(a_matrix,75))


  

Sum: 120
Min: 0
Max: 15
Media: 7.5
Mediana: 7.5
Moda: ModeResult(mode=array([0, 1, 2, 3]), count=array([1, 1, 1, 1]))
Varianza: 21.25
Desviacion Estandar: 4.6097722286464435
Percentil 25: 3.75
Percentil 50: 7.5
Percentil 75: 11.25


In [ ]:
# Estadísticos descriptivos con numpy axis=0 columnas, axis=1 filas
print("Sum:", np.sum(a_matrix, axis=0))
print("Min:", np.min(a_matrix, axis=0))
print("Max:", np.max(a_matrix, axis=0))
print("Media:", np.mean(a_matrix, axis=0))
print("Mediana:", np.median(a_matrix, axis=0))
print("Moda:", stats.mode(a_matrix, axis=0))
print("Varianza:", np.var(a_matrix, axis=0))
print("Desviacion Estandar:", np.std(a_matrix,axis=0))
print("Percentil 25:", np.percentile(a_matrix,25,axis=0))
print("Percentil 50:", np.percentile(a_matrix,50,axis=0))
print("Percentil 75:", np.percentile(a_matrix,75,axis=0))


Sum: [24 28 32 36]
Min: [0 1 2 3]
Max: [12 13 14 15]
Media: [6. 7. 8. 9.]
Mediana: [6. 7. 8. 9.]
Moda: ModeResult(mode=array([0, 1, 2, 3]), count=array([1, 1, 1, 1]))
Varianza: [20. 20. 20. 20.]
Desviacion Estandar: [4.47213595 4.47213595 4.47213595 4.47213595]
Percentil 25: [3. 4. 5. 6.]
Percentil 50: [6. 7. 8. 9.]
Percentil 75: [ 9. 10. 11. 12.]


# Estadísticos descriptivos con Pandas

In [57]:
ds = pd.Series(np.arange(0,16))
ds

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
dtype: int64

In [58]:
print("Minimo:", ds.min())
print("Maximo:", ds.max())
print("Media:", ds.mean())
print("Mediana:", ds.median())
print("Moda:", ds.mode()[0])
print("Varianza:", ds.var())        
print("Desviacion Estandar:", ds.std())
print("Percentil 25:", ds.quantile(0.25))
print("Percentil 50:", ds.quantile(0.50))
print("Percentil 75:", ds.quantile(0.75))   


Minimo: 0
Maximo: 15
Media: 7.5
Mediana: 7.5
Moda: 0
Varianza: 22.666666666666668
Desviacion Estandar: 4.760952285695233
Percentil 25: 3.75
Percentil 50: 7.5
Percentil 75: 11.25


## Ejercicios 

Ejercicio 1. Cree una serie de pandas de dos maneras diferentes a partir de la lista: [1, 3, 5, …, 33]. Además, cree una serie pandas de dos maneras diferentes a partir del ndarray: [4, 8, 12, …, 44].

In [64]:
base_lista = list(range(1, 34)) 
impares_slice = base_lista[::2]

serie_impares_b = pd.Series(data=impares_slice)

serie_impares_b

0      1
1      3
2      5
3      7
4      9
5     11
6     13
7     15
8     17
9     19
10    21
11    23
12    25
13    27
14    29
15    31
16    33
dtype: int64

Ejercicio 2 : Cree una función para calcular la varianza poblacional y otra para calcular la varianza muestral que admita como argumento un ndarray. Aplíquelo al siguiente conjunto de edades: 22, 18, 35, 23, 41, 28, 45, y compare los resultados con los obtenidos mediante los métodos de numpy para calcular la varianza poblacional y muestral.

In [ ]:
import numpy as np

data = np.array([22, 18, 35, 23, 41, 28, 45])

data

array([22, 18, 35, 23, 41, 28, 45])