In [21]:
'''
Módulo 2 : Estadística y Visualización de Datos
Sesión : 01
Fecha : 25/10/2025
Actualización : 25/04/2026
'''
print("Módulo 2 : Estadística y Visualización de Datos")

Módulo 2 : Estadística y Visualización de Datos


- Documentación Numpy : https://numpy.org/doc/stable/reference/index.html#reference

## 1. Trabajando con listados

Objetivo: comparar el uso de listas de Python con arreglos de NumPy para entender ventajas de vectorizacion y metadatos (`dtype`, `shape`, `ndim`).

In [ ]:
import numpy as np

# Creando un array a partir de una lista
nro_list= [1, 2, 3, 4, 5]
nro_array = np.array(nro_list)

print("Lista type :", type(nro_list))
print("Array type :", type(nro_array))

# Creando un array directamente
nro_array = np.array([1, 2, 3, 4, 5])


Lista type : <class 'list'>
Array type : <class 'numpy.ndarray'>


In [18]:
import numpy as np

nros = [ x for x in range(5000)]
# print(nros)

In [19]:
# Creando un array a partir de una lista
np_nros = np.array(nros)
print(np_nros)

[   0    1    2 ... 4997 4998 4999]


In [ ]:
print("np_nros.dtype :", np_nros.dtype)
print("np_nros.ndim :", np_nros.ndim)
print("np_nros.size :", np_nros.size)
print("np_nros.shape :", np_nros.shape)
print("np_nros.itemsize :", np_nros.itemsize)
print("np_nros.data :", np_nros.data)


np_nros.dtype : int64
np_nros.ndim : 1
np_nros.size : 5000
np_nros.shape : (5000,)
np_nros.itemsize : 8
np_nros.data : <memory at 0x108c60e80>


## Ejercicio

-  Crear un arreglo numpy con los numeros 3,6,9, ...., 99

In [23]:
nros = [ 3*x for x in range(1,34)]
np_nros = np.array(nros)

In [24]:
import numpy as np

Ejercicio = [ x for x in range(3,100)]
np_nros = np.array(Ejercicio)
print(np_nros)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]


In [25]:
arreglo = np.arange(3, 100, 3)
print(arreglo)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [26]:
import numpy as np

nros = [x for x in range(3, 100, 3)] 
np_nros = np.array(nros) 

print(np_nros)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [ ]:
nros = [ x for x in range(3,100,3) ]
nro_array = np.array(nros)
print(nros)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96]


## 2. Trabajando con arreglos

Objetivo: crear arreglos 2D y revisar atributos clave para interpretar su estructura.

In [31]:
nros = [
        [ x for x in range(10)],
        [ y for y in range(10)],
        [ z for z in range(10)]
    ]
print(nros)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]


In [33]:
np_nros = np.array(nros)
np_nros

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
print("np_nros.dtype :", np_nros.dtype)
print("np_nros.ndim :", np_nros.ndim)
print("np_nros.size :", np_nros.size)
print("np_nros.shape :", np_nros.shape)
print("np_nros.itemsize :", np_nros.itemsize)
print("np_nros.data :", np_nros.data)

np_nros.dtype : int64
np_nros.ndim : 2
np_nros.size : 30
np_nros.shape : (3, 10)
np_nros.itemsize : 8
np_nros.data : <memory at 0x10846a670>


### Ejercicio 1

Crea un arreglo de NumPy con 3 filas:
- Fila 1: los 10 primeros números pares.
- Fila 2: los 10 primeros números impares.
- Fila 3: secuencia 10, 30, 50, ..., 110.

Pista: puedes usar `np.arange(inicio, fin, paso)` y luego combinar las secuencias en una sola matriz.

In [ ]:
# TO DO
# 1) Crea tres arreglos 1D segun el enunciado.
# 2) Unelos en una matriz de 3 filas.
# 3) Verifica la forma esperada con .shape.

In [42]:
nros = [
    [ x for x in range(0,12,2)],
    [ y for y in range(1,13,2)],
    [ z for z in range(10,130,20)]
]
print(nros)

[[0, 2, 4, 6, 8, 10], [1, 3, 5, 7, 9, 11], [10, 30, 50, 70, 90, 110]]


In [41]:
nros = [
    [ x for x in range(0,20,2)],
    [ y for y in range(1,21,2)],
    [ z for z in range(10,110,10)]
]
print(nros)
np_nros = np.array(nros)
print(np_nros)

[[0, 2, 4, 6, 8, 10, 12, 14, 16, 18], [1, 3, 5, 7, 9, 11, 13, 15, 17, 19], [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]]
[[  0   2   4   6   8  10  12  14  16  18]
 [  1   3   5   7   9  11  13  15  17  19]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [37]:
import numpy as np

fila1 = [2*x for x in range(6)]        # 0,2,4,6,8,10
fila2 = [2*x + 1 for x in range(6)]    # 1,3,5,7,9,11
fila3 = [20*x + 10 for x in range(6)]  # 10,30,50,70,90,110

np_nros = np.array([fila1, fila2, fila3])

print(np_nros)

[[  0   2   4   6   8  10]
 [  1   3   5   7   9  11]
 [ 10  30  50  70  90 110]]


In [ ]:
import numpy as np

fila1 = np.arange(0, 11, 2) 
fila2 = np.arange(1, 12, 2)
fila3 = np.arange(10, 111, 20)
matriz = np.array([fila1, fila2, fila3])

print("Matriz resultante:")
print(matriz)

Matriz resultante:
[[  0   2   4   6   8  10]
 [  1   3   5   7   9  11]
 [ 10  30  50  70  90 110]]


## 3. Creación de arreglos NumPy

Objetivo: practicar constructores frecuentes (`zeros`, `ones`, `arange`) para generar arreglos de forma rapida.

In [43]:
np_z = np.zeros((3, 4))  # Arreglo de ceros de 3 filas y 4 columnas    
np_z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np_o = np.ones((2, 5))  # Arreglo de unos de 2 filas y 5 columnas    
np_o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np_nros = np.arange(10, 51)  # Arreglo con valores desde 10 hasta 50
np_nros

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

## 4. Operaciones basicas

Objetivo: aplicar operaciones aritmeticas vectorizadas y comparar con listas tradicionales.

In [48]:
# Como sumamos a una lista un valor escalar?
arr1 = range(4)
print("arr1 :", arr1)
# print("arr1 + 5 :", arr1 + 5) # Esto generará un error
print("arr1 + 5 :", [x + 5 for x in arr1])  # Suma 5 a cada elemento usando comprensión de listas

arr1 : range(0, 4)
arr1 + 5 : [5, 6, 7, 8]


In [49]:
# SUMA Y MULTIPLICACION CON NUMPY
np_arr1 = np.arange(4)
print("np_arr1 :", np_arr1)
print("Suma 5 a cada elemento de np_arr1 :",np_arr1  + 5 )  # Suma 5 a cada elemento
print("Multiplica por 5 a cada elemento de np_arr1 :",np_arr1  * 5 )  # Multiplicar por 5 a cada elemento

np_arr1 : [0 1 2 3]
Suma 5 a cada elemento de np_arr1 : [5 6 7 8]
Multiplica por 5 a cada elemento de np_arr1 : [ 0  5 10 15]


In [50]:
# RESTA Y DIVISION CON NUMPY
np_arr1 = np.arange(4,8)
print("np_arr1 :", np_arr1)
print("Resta 5 a cada elemento de np_arr1 :",np_arr1  - 5 )  # Resta 5 a cada elemento
print("Divide 5 a cada elemento de np_arr1 :",np_arr1  / 5 )  # Divide 5 a cada elemento

np_arr1 : [4 5 6 7]
Resta 5 a cada elemento de np_arr1 : [-1  0  1  2]
Divide 5 a cada elemento de np_arr1 : [0.8 1.  1.2 1.4]


### Ejercicio 2

Crea un arreglo de NumPy con la secuencia 10, 30, 50, ..., 130. Luego aplica en cadena estas operaciones:
- Divide todos los elementos entre 10.
- Resta 3 al resultado anterior.
- Suma 1 al resultado anterior.
- Multiplica por -1 el resultado final y muestralo.

Pista: usa una variable intermedia por cada paso para revisar tu proceso.

In [ ]:
# TO DO
# 1) Genera la secuencia con arange (ajustando el paso).
# 2) Aplica cada transformacion en orden.
# 3) Imprime el resultado final.

In [53]:
arreglo = np.arange(10, 131, 20)  # 10,30,50,...,130
print("Inicial:", arreglo)
op1 = arreglo / 10
print("Dividido entre 10:", op1)
op2 = op1 - 3
print("Restando 3:", op2)
op3 = op2 + 1
print("Sumando 1:", op3)
resultado = op3 * -1
print("Resultado final:", resultado)

Inicial: [ 10  30  50  70  90 110 130]
Dividido entre 10: [ 1.  3.  5.  7.  9. 11. 13.]
Restando 3: [-2.  0.  2.  4.  6.  8. 10.]
Sumando 1: [-1.  1.  3.  5.  7.  9. 11.]
Resultado final: [  1.  -1.  -3.  -5.  -7.  -9. -11.]


In [55]:
np_arr1 = np.arange(10,150,20)
print("np_arr1 :", np_arr1)
print("Resta 5 a cada elemento de np_arr1 :",np_arr1 / 10 )  
print("Divide 5 a cada elemento de np_arr1 :",np_arr1 - 3 )  
print("Divide 5 a cada elemento de np_arr1 :",np_arr1 + 1 )
print("Divide 5 a cada elemento de np_arr1 :",np_arr1 * -1)

np_arr1 : [ 10  30  50  70  90 110 130]
Resta 5 a cada elemento de np_arr1 : [ 1.  3.  5.  7.  9. 11. 13.]
Divide 5 a cada elemento de np_arr1 : [  7  27  47  67  87 107 127]
Divide 5 a cada elemento de np_arr1 : [ 11  31  51  71  91 111 131]
Divide 5 a cada elemento de np_arr1 : [ -10  -30  -50  -70  -90 -110 -130]


In [59]:
import numpy as np

Secuencia = np.arange (10,131,20)
Resultado1 = Secuencia / 10
Resultado2 = Resultado1 - 3
Resultado3 = Resultado2 + 1
ResultadoFinal = Resultado3 * -1

print(Secuencia)
print(Resultado1)
print(Resultado2)
print(Resultado3)
print(ResultadoFinal)

[ 10  30  50  70  90 110 130]
[ 1.  3.  5.  7.  9. 11. 13.]
[-2.  0.  2.  4.  6.  8. 10.]
[-1.  1.  3.  5.  7.  9. 11.]
[  1.  -1.  -3.  -5.  -7.  -9. -11.]


### Operaciones entre arreglos


In [56]:
np_arr1 = np.arange(4)      
np_arr2 = np.arange(4,8)

print("np_arr1 :", np_arr1)
print("np_arr2 :", np_arr2)  


np_arr1 : [0 1 2 3]
np_arr2 : [4 5 6 7]


In [57]:
print("Suma de np_arr1 + np_arr2 :", np_arr1 + np_arr2)
print("Resta de np_arr1 - np_arr2 :", np_arr1 - np_arr2)
print("Multiplicacion de np_arr1 * np_arr2 :", np_arr1 * np_arr2)
print("Division de np_arr1 / np_arr2 :", np_arr1 / np_arr2)

Suma de np_arr1 + np_arr2 : [ 4  6  8 10]
Resta de np_arr1 - np_arr2 : [-4 -4 -4 -4]
Multiplicacion de np_arr1 * np_arr2 : [ 0  5 12 21]
Division de np_arr1 / np_arr2 : [0.         0.2        0.33333333 0.42857143]


In [58]:
(np_arr1 / np_arr2)*np_arr2

array([0., 1., 2., 3.])

### Ejercicio 3

Se tienen los arreglos:
- [0, 1, 0]
- [1, 0, 0]
- [0, 0, 1]

Calcula:
- La suma entre arreglos.
- El producto entre arreglos.

Pista: define cada arreglo como `np.array(...)` y prueba operaciones elemento a elemento.

In [ ]:
# TO DO
# 1) Crea los tres arreglos.
# 2) Realiza la suma solicitada.
# 3) Realiza el producto solicitado.
# 4) Muestra resultados con print().

In [60]:
a = np.array([0, 1, 0])
b = np.array([1, 0, 0])
c = np.array([0, 0, 1])

suma = a + b + c
print("Suma:", suma)
producto = a * b * c
print("Producto:", producto)

Suma: [1 1 1]
Producto: [0 0 0]


In [61]:
import numpy as np

arreglo1 = np.array([0, 1, 0])
arreglo2 = np.array([1, 0, 0])
arreglo3 = np.array([0, 0, 1])

suma = arreglo1 + arreglo2 + arreglo3
print("Resultado de la suma:", suma)

producto = arreglo1 * arreglo2 * arreglo3
print("Resultado del producto:", producto)

Resultado de la suma: [1 1 1]
Resultado del producto: [0 0 0]


In [62]:

a = np.array([0, 1, 0])
b = np.array([1, 0, 0])
c = np.array([0, 0, 1])

suma = a + b + c

producto = a * b * c
#Resultado
print (f"la suma de las matrices es:{suma}")
print (f"el producto de las matrices es:{producto}")

la suma de las matrices es:[1 1 1]
el producto de las matrices es:[0 0 0]


In [63]:
import numpy as np
x = np.array([0,1,0])
y = np.array([1,0,0])
z = np.array([0,0,1])


#SUMA DE ARREGLOS
suma_arreglo = x + y + z


#PRODUCTO DE ARREGLOS
producto_arreglo = x * y * z


print("Suma de arreglos:", suma_arreglo)
print("Producto de arreglos:", producto_arreglo)

Suma de arreglos: [1 1 1]
Producto de arreglos: [0 0 0]


In [64]:
import numpy as np
a = np.array([0,1,0])
b = np.array([1,0,0])
c = np.array([0,0,1])

suma = a+b+c
producto = a*b*c
print("Suma: ",suma)
print("Producto: ",producto)

Suma:  [1 1 1]
Producto:  [0 0 0]


## 5. Producto de matrices

Objetivo: interpretar el producto punto y su uso en operaciones matriciales.

<img src="imagenes/producto_punto.jpg" width="400" />

In [65]:
a_arr = np.arange(4)      
b_arr = np.arange(4,8)

print("a_arr :", a_arr)
print("b_arr :", b_arr)

a_arr : [0 1 2 3]
b_arr : [4 5 6 7]


In [ ]:
print(a_arr * b_arr)

print(sum(a_arr * b_arr))

print(np.dot(a_arr, b_arr))  # Producto punto de a_arr y b_arr
print(np.dot(b_arr, a_arr))  # Producto punto de b_arr y a_arr

print(a_arr.dot(b_arr))  # Producto punto de a_arr y b_arr
print(b_arr.dot(a_arr))  # Producto punto de b_arr y a_arr


[ 0  5 12 21]
38
38
38
38
38


In [69]:
a_arr = np.array([[1, 2], [3, 4]])
b_arr = np.array([[5, 6], [7, 8]])      

print("a_arr :\n", a_arr)
print("b_arr :\n", b_arr)

c_arr = a_arr.dot(b_arr)
print("Producto de matrices a_arr . b_arr :\n", c_arr)  

c_arr = np.dot(a_arr,b_arr)
print("Producto de matrices a_arr . b_arr :\n", c_arr)  


a_arr :
 [[1 2]
 [3 4]]
b_arr :
 [[5 6]
 [7 8]]
Producto de matrices a_arr . b_arr :
 [[19 22]
 [43 50]]
Producto de matrices a_arr . b_arr :
 [[19 22]
 [43 50]]


### Cambiar la forma de un arreglo


In [70]:
np_arr = np.arange(12)  # Arreglo con valores del 0 al 11
print("Arreglo original:")
print(np_arr)


Arreglo original:
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [71]:
np_arr_reshaped = np_arr.reshape((3, 4))  # Cambiar la forma a 3 filas y 4 columnas
print("Arreglo con nueva forma (3x4):")
print(np_arr_reshaped)

Arreglo con nueva forma (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Ejercicio 4

Dados los vectores:
- A = [3, 4]
- B = [2, 5]

Calcula:
- El producto punto `A · B`.
- Las magnitudes `|A|` y `|B|`.

Pista: puedes usar `np.dot` y `np.linalg.norm`.

In [ ]:
# TO DO
# 1) Define los vectores A y B como np.array.
# 2) Calcula el producto punto.
# 3) Calcula las magnitudes de ambos vectores.
# 4) Muestra los resultados.

In [72]:
A = np.array([3, 4])
B = np.array([2, 5])
producto_punto = np.dot(A, B)
print("Producto punto:", producto_punto)
modulo_A = np.linalg.norm(A)
modulo_B = np.linalg.norm(B)

print("|A|:", modulo_A)
print("|B|:", modulo_B)

Producto punto: 26
|A|: 5.0
|B|: 5.385164807134504


In [73]:
A = np.array([3, 4])
B = np.array([2, 5])
producto_punto = np.dot(A, B)
magnitud_A = np.linalg.norm(A)
magnitud_B = np.linalg.norm(B)

print (magnitud_A)
print (magnitud_B)

5.0
5.385164807134504


In [76]:
a_arr = np.array([3, 4]) 
b_arr = np.array([2, 5])

print("a_arr :\n", a_arr) 
print("b_arr :\n", b_arr)

c_arr = a_arr.dot(b_arr) 
print("Producto de matrices a_arr . b_arr :\n", c_arr)

a_arr :
 [3 4]
b_arr :
 [2 5]
Producto de matrices a_arr . b_arr :
 26


In [77]:

A = np.array([3, 4])
B = np.array([2, 5])

producto_elemental = A * B

producto_punto = np.dot(A, B)

magnitud_A = np.linalg.norm(A)
magnitud_B = np.linalg.norm(B)

print(f"Producto elemento a elemento (A*B): {producto_elemental}")
print(f"Producto punto (A·B): {producto_punto}")
print(f"Magnitud |A|: {magnitud_A}")
print(f"Magnitud |B|: {magnitud_B}")



Producto elemento a elemento (A*B): [ 6 20]
Producto punto (A·B): 26
Magnitud |A|: 5.0
Magnitud |B|: 5.385164807134504


In [78]:

A = np.array([3, 4])
B = np.array([2, 5])

producto_elemental = A * B

producto_punto = np.dot(A, B)

magnitud_A = np.linalg.norm(A)
magnitud_B = np.linalg.norm(B)

print(f"Producto elemento a elemento (A*B): {producto_elemental}")
print(f"Producto punto (A·B): {producto_punto}")
print(f"Magnitud |A|: {magnitud_A}")
print(f"Magnitud |B|: {magnitud_B}")



Producto elemento a elemento (A*B): [ 6 20]
Producto punto (A·B): 26
Magnitud |A|: 5.0
Magnitud |B|: 5.385164807134504


## 6. Funciones utilitarias

Objetivo: usar funciones de agregacion y estadistica descriptiva con NumPy.

In [74]:
a_arr = np.arange(4,8)
print("a_arr :", a_arr)

# Elevar a una potencia cada elemento
print("a_arr elevado al cubo :", np.power(a_arr, 3))

# Sumar todos los elementos del arreglo
print("Suma de todos los elementos de a_arr :", np.sum(a_arr))

# Obtener el valor minimo de todos los elementos
print("Valor minimo de a_arr :", np.min(a_arr))

# Obtener el valor maximo de todos los elementos
print("Valor maximo de a_arr :", np.max(a_arr)) 

# Calcular la media de los elementos
print("Media de los elementos de a_arr :", np.mean(a_arr))

# Calcular la desviacion estandar de los elementos
print("Desviacion estandar de los elementos de a_arr :", np.std(a_arr))

# Calcular la varianza de los elementos
print("Varianza de los elementos de a_arr :", np.var(a_arr))    

# Calcular la raiz cuadrada de cada elemento
print("Raiz cuadrada de cada elemento de a_arr :", np.sqrt(a_arr))  



a_arr : [4 5 6 7]
a_arr elevado al cubo : [ 64 125 216 343]
Suma de todos los elementos de a_arr : 22
Valor minimo de a_arr : 4
Valor maximo de a_arr : 7
Media de los elementos de a_arr : 5.5
Desviacion estandar de los elementos de a_arr : 1.118033988749895
Varianza de los elementos de a_arr : 1.25
Raiz cuadrada de cada elemento de a_arr : [2.         2.23606798 2.44948974 2.64575131]


### Ejercicio 6

Dadas las notas de 2 estudiantes en 5 cursos:
- estudiante_A = np.array([18, 14, 20, 10, 15])
- estudiante_B = np.array([17, 16, 17, 14, 18])

Construye una tabla comparativa con:
- Nota promedio
- Nota minima
- Nota maxima

Pista: usa `np.mean`, `np.min` y `np.max`.

In [ ]:
# TO DO
# 1) Define ambos arreglos de notas.
# 2) Calcula promedio, minima y maxima para cada estudiante.
# 3) Presenta los resultados en una estructura comparativa.

In [79]:
Estudiante_A = np.array([18, 14, 20, 10, 15]) 
Estudiante_B = np.array([17, 16, 17, 14, 18])

print("Media de los elementos de Estudiante_A :", np.mean(Estudiante_A))
print("Media de los elementos de Estudiante_B :", np.mean(Estudiante_B))
print("Valor minimo de Estudiante_A :", np.min(Estudiante_A))
print("Valor minimo de Estudiante_B :", np.min(Estudiante_B))

Media de los elementos de Estudiante_A : 15.4
Media de los elementos de Estudiante_B : 16.4
Valor minimo de Estudiante_A : 10
Valor minimo de Estudiante_B : 14


In [80]:
estudiante_A = np.array([18, 14, 20, 10, 15])
estudiante_B = np.array([17, 16, 17, 14, 18])
prom_A = np.mean(estudiante_A)
min_A = np.min(estudiante_A)
max_A = np.max(estudiante_A)

prom_B = np.mean(estudiante_B)
min_B = np.min(estudiante_B)
max_B = np.max(estudiante_B)

print("Promedio")
print(f"A  {prom_A}|B  {prom_B}")
print("Nota mínima")
print(f"A  {min_A}  |B  {min_B}")
print("Nota máxima")

Promedio
A  15.4|B  16.4
Nota mínima
A  10  |B  14
Nota máxima


In [85]:
import pandas as pd

estudiante_A = np.array([18, 14, 20, 10, 15])
estudiante_B = np.array([17, 16, 17, 14, 18])

promedio_A = np.mean(estudiante_A)
min_A = np.min(estudiante_A)
max_A = np.max(estudiante_A)

promedio_B = np.mean(estudiante_B)
min_B = np.min(estudiante_B)
max_B = np.max(estudiante_B)

datos = {
  "Métrica": ["Nota Promedio", "Nota Mínima", "Nota Máxima"],
  "Estudiante A": [promedio_A, min_A, max_A],
  "Estudiante B": [promedio_B, min_B, max_B]
}

tabla = pd.DataFrame(datos)

print(tabla)

         Métrica  Estudiante A  Estudiante B
0  Nota Promedio          15.4          16.4
1    Nota Mínima          10.0          14.0
2    Nota Máxima          20.0          18.0


In [86]:
import numpy as np

estudiante_A = np.array([18, 14, 20, 10, 15])
estudiante_B = np.array([17, 16, 17, 14, 18])

prom_A = np.mean(estudiante_A)
min_A = np.min(estudiante_A)
max_A = np.max(estudiante_A)

prom_B = np.mean(estudiante_B)
min_B = np.min(estudiante_B)
max_B = np.max(estudiante_B)

print(f" el promedio de A es: {prom_A} y el de B es {prom_B} ")
print(f" el Min de A es: {min_B} y el de B es {min_B} ")
print(f" el Max de A es: {max_B} y el de B es {max_B} ")

 el promedio de A es: 15.4 y el de B es 16.4 
 el Min de A es: 14 y el de B es 14 
 el Max de A es: 18 y el de B es 18 


## 7. Iteraciones por columnas y filas

Objetivo: practicar agregaciones por ejes (`axis=0` y `axis=1`) en matrices.

In [87]:
a_arr = np.arange(0,12).reshape((3,4))
print("a_arr :\n", a_arr)


a_arr :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Sumas
COL = 0 # Para procesar por columnas, el eje es 0
FILA = 1 # Para procesar por filas, el eje es 1

# Procesar por columnas
col_proc = np.apply_along_axis(np.sum, axis=COL, arr=a_arr)
print("Suma por columnas :", col_proc)

# Procesar por filas
filas_proc = np.apply_along_axis(np.sum, axis=FILA, arr=a_arr)
print("Suma por filas :", filas_proc)

Suma por columnas : [12 15 18 21]
Suma por filas : [ 6 22 38]


In [90]:
# Promedios

# Procesar por columnas
col_proc = np.apply_along_axis(np.mean, axis=COL, arr=a_arr)
print("Promedio por columnas :", col_proc)

# Procesar por filas
filas_proc = np.apply_along_axis(np.mean, axis=FILA, arr=a_arr)
print("Promedio por filas :", filas_proc)

Promedio por columnas : [4. 5. 6. 7.]
Promedio por filas : [1.5 5.5 9.5]


In [91]:

a_arr = np.arange(0,12).reshape((3,4))
print("a_arr :\n", a_arr)

a_arr :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [94]:
def potencia(x):
    return x ** 2


b_arr =  np.apply_along_axis(potencia, axis=FILA, arr=a_arr)
print("b_arr :\n", b_arr)

b_arr :
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


### Ejercicio 7

Dado el PBI de Chile, Perú y Colombia entre 2020 y 2029, calcula:
- El promedio del PBI de los 3 paises por año.
- El promedio historico del PBI de cada pais (2020-2029).

Datos:
- Perú -> 209,057 228,704  248,179	272,755	295,220	341,025	380,900	386,375	402,720	418,912
- Chile -> 254,060	315,411	301,270	335,627	330,210	355,346	407,850	434,037	455,022	475,623
- Colombia -> 270,348	318,525	345,632	366,901	420,504	457,410	539,530	554,384	578,238	604,409

Crea arreglos para cada pais (sin incluir los nombres):
- `peru = np.array([...])`
- `chile = np.array([...])`
- `colombia = np.array([...])`

Pista: apila los arreglos en una sola matriz y usa operaciones por eje.

In [118]:
peru = np.array([209984, 229832, 248204, 271780, 294675, 318480, 326608])
chile = np.array([254060, 315411, 301270, 335627, 330210, 347174, 363299])
colombia = np.array([270348, 318525, 345632, 366292, 418818, 438121, 462251])

pbi_total = np.array([peru, chile, colombia])

print (f"la matriz de 3 filas y 7 columnas es: \n {pbi_total}")

promedio_por_anho = np.apply_along_axis(np.mean, axis=COL, arr=pbi_total)
print (f"el promedio por año de estos tres paises es \n:{np.round(promedio_por_anho,0)}")

promedio_por_pais = np.apply_along_axis(np.mean, axis=FILA, arr=pbi_total)
print (f"el promedio por año de cada pais es\n :{promedio_por_pais}")

la matriz de 3 filas y 7 columnas es: 
 [[209984 229832 248204 271780 294675 318480 326608]
 [254060 315411 301270 335627 330210 347174 363299]
 [270348 318525 345632 366292 418818 438121 462251]]
el promedio por año de estos tres paises es 
:[244797. 287923. 298369. 324566. 347901. 367925. 384053.]
el promedio por año de cada pais es
 :[271366.14285714 321007.28571429 374283.85714286]


In [ ]:
# TO DO
# 1) Crea los arreglos Perú, Chile y Colombia.
# 2) Construye una matriz con los tres paises.
# 3) Calcula promedios por año y por pais usando axis.
# 4) Muestra resultados con etiquetas claras.

In [102]:
peru = np.array([209057 ,228704 ,248179, 272755 ,295220 ,341025 ,380900 ,386375 ,402720, 418912])
chile = np.array([254060 ,315411, 301270 ,335627 ,330210 ,355346 ,407850, 434037, 455022 ,475623])
colombia = np.array([270348 ,318525,345632, 366901, 420504, 457410, 539530, 554384, 578238, 604409])

pbi = np.array([peru, chile, colombia])

columna = 0
fila = 1

prom_anual = np.apply_along_axis(np.mean, axis=columna, arr=pbi)
print("Promedio de los tres paises anual:", prom_anual)
prom_pais = np.apply_along_axis(np.mean, axis=fila, arr=pbi)
print("Promedio histórico de cada país:", prom_pais)

Promedio de los tres paises anual: [244488.33333333 287546.66666667 298360.33333333 325094.33333333
 348644.66666667 384593.66666667 442760.         458265.33333333
 478660.         499648.        ]
Promedio histórico de cada país: [318384.7 366445.6 445588.1]


In [103]:
import numpy as np

peru = np.array([209984, 229832, 248204, 271780, 294675, 318480, 326608])
chile = np.array([254060, 315411, 301270, 335627, 330210, 347174, 363299])
colombia = np.array([270348, 318525, 345632, 366292, 418818, 438121, 462251])
#matriz
matriz = np.array([peru,chile,colombia])
#promedio por año
prom_anual =  np.apply_along_axis(np.mean,axis=0,arr=matriz)
prom_pais =  np.apply_along_axis(np.mean,axis=1,arr=matriz)

print("Promedio del PBI por año: ")
print(prom_anual)

print("Promedio histórico por país:")
print("Perú:", prom_pais[0])
print("Chile:", prom_pais[1])
print("Colombia:", prom_pais[2])

Promedio del PBI por año: 
[244797.33333333 287922.66666667 298368.66666667 324566.33333333
 347901.         367925.         384052.66666667]
Promedio histórico por país:
Perú: 271366.14285714284
Chile: 321007.28571428574
Colombia: 374283.85714285716


In [105]:

Peru = np.array ([209057, 228704, 248179, 272755, 295220, 341025, 380900, 386375, 402720, 418912])
Chile = np.array ([254060, 315411, 301270, 335627, 330210, 355346, 407850, 434037, 455022, 475623])
Colombia = np.array ([270348,  318525, 345632, 366901, 420504, 457410, 539530, 554384, 578238, 604409])

#PBI promedio
Peru_PBI_Prom = np.mean (Peru)
Chile_PBI_Prom = np.mean (Chile)
Colombia_PBI_Prom = np.mean (Colombia)

#PBI historico

Peru_PBI_Historico = np.max (Peru)
Chile_PBI_Historico = np.max (Chile)
Colombia_PBI_Historico = np.max (Colombia)

print (f"Peru_PBI_Prom:", Peru_PBI_Prom)
print (f"Chile_PBI_Prom:", Chile_PBI_Prom)
print (f"Colombia_PBI_Prom:", Colombia_PBI_Prom)
print (f"Peru_PBI_Historico:", Peru_PBI_Historico)
print (f"Chile_PBI_Historico:", Chile_PBI_Historico)
print (f"Colombia_PBI_Historico:", Colombia_PBI_Historico)

Peru_PBI_Prom: 318384.7
Chile_PBI_Prom: 366445.6
Colombia_PBI_Prom: 445588.1
Peru_PBI_Historico: 418912
Chile_PBI_Historico: 475623
Colombia_PBI_Historico: 604409


## 8. Condiciones y expresiones booleanas

Objetivo: filtrar datos con condiciones y mascaras booleanas.

In [119]:
a_arr = np.arange(0,12).reshape((3,4))
print("a_arr :\n", a_arr)

# Condiciones y expresio
print(a_arr > 5)

a_arr :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [120]:
a_arr[a_arr > 5]

array([ 6,  7,  8,  9, 10, 11])

### Ejercicio 8

Dadas las notas de 2 estudiantes:
- `estudiante_A = np.array([18, 14, 20, 10, 15])`
- `estudiante_B = np.array([17, 16, 17, 14, 18])`

Calcula:
- El promedio general de todas las notas.
- Las notas que son mayores a ese promedio.

Pista: combina ambos arreglos y utiliza una mascara booleana para filtrar.

In [ ]:
# TO DO
# 1) Define ambos arreglos de notas.
# 2) Combina las notas en un solo arreglo.
# 3) Calcula el promedio general.
# 4) Filtra las notas mayores al promedio.

In [123]:
estudiante_A = np.array([18, 14, 20, 10, 15])
estudiante_B = np.array([17, 16, 17, 14, 18])
matriz_estudiantes = np.array([estudiante_A, estudiante_B])
print(matriz_estudiantes)
print(np.mean(matriz_estudiantes))
Promedio = np.apply_along_axis(np.mean, axis=1, arr=matriz_estudiantes)
print(f"Promedio de estudiantes (estudiante_A, estudiante_B) son: {Promedio}")
a_arr = estudiante_A
a_arr1 = estudiante_B
a_arr[a_arr > 15.4]
a_arr1[a_arr1 > 16.4]

[[18 14 20 10 15]
 [17 16 17 14 18]]
15.9
Promedio de estudiantes (estudiante_A, estudiante_B) son: [15.4 16.4]


array([17, 17, 18])

In [124]:
import numpy as np

estudiante_A = np.array([18, 14, 20, 10, 15])
estudiante_B = np.array([17, 16, 17, 14, 18])

notas_generales = np.array((estudiante_A, estudiante_B))
prom_general = np.mean(notas_generales)
notas_mayores = notas_generales[notas_generales > prom_general]

print(f"El promedio General es: {prom_general}")
print(f"Notas mayores al promedio son: {notas_mayores}")

El promedio General es: 15.9
Notas mayores al promedio son: [18 20 17 16 17 18]


In [125]:
import numpy as np
estudiante_A = np.array([18, 14, 20, 10, 15])
estudiante_B = np.array([17, 16, 17, 14, 18])
todas_las_notas = np.concatenate([estudiante_A, estudiante_B])
promedio_general = np.mean(todas_las_notas)
mascara = todas_las_notas > promedio_general
notas_superiores = todas_las_notas[mascara]
print(f"Promedio general de todas las notas: {promedio_general}")
print(f"Notas mayores al promedio: {notas_superiores}")

Promedio general de todas las notas: 15.9
Notas mayores al promedio: [18 20 17 16 17 18]


In [126]:
estudiante_A = np.array([18, 14, 20, 10, 15])
estudiante_B = np.array([17, 16, 17, 14, 18])

todas = np.array((estudiante_A, estudiante_B))
print("Todas las notas:\n", todas)

promedio = np.mean(todas)
print("Promedio general:", promedio)

mayores = todas > promedio
print("Máscara:\n", mayores)

notas_mayores = todas[mayores]
print("Notas mayores al promedio:", notas_mayores)

Todas las notas:
 [[18 14 20 10 15]
 [17 16 17 14 18]]
Promedio general: 15.9
Máscara:
 [[ True False  True False False]
 [ True  True  True False  True]]
Notas mayores al promedio: [18 20 17 16 17 18]


## 9. Cambio de dimensión de un arreglo

Objetivo: transformar la forma de un arreglo sin alterar sus datos.

In [127]:
# Creacion de un arreglo aleatorio, de 3 x4 
a_arr = np.random.random((3,4))
print("a_arr :\n", a_arr)

# Cambio de dimension de un arreglo
print(a_arr.ravel())

a_arr :
 [[0.41846803 0.19691486 0.98562272 0.53514747]
 [0.40219104 0.12745855 0.17902654 0.51670828]
 [0.04607418 0.16925047 0.09772343 0.90932947]]
[0.41846803 0.19691486 0.98562272 0.53514747 0.40219104 0.12745855
 0.17902654 0.51670828 0.04607418 0.16925047 0.09772343 0.90932947]


In [132]:
a_arr = np.arange(1,13).reshape((3,4))
print("a_arr :\n", a_arr)

a_arr :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [133]:
a_arr_flat = a_arr.ravel()
print("a_arr_flat :\n", a_arr_flat)

a_arr_flat :
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


## 10. Transpuesta de matrices

Objetivo: comprender el intercambio entre filas y columnas usando `.T` o `np.transpose`.

In [134]:
# Creacion de un arreglo aleatorio, de 1x2 
#a_arr = np.random.random((1,2))
a_arr = np.arange(1,4).reshape((1,3))
print("a_arr :\n", a_arr)

# Generacion de matriz transpuesta
print("Matriz transpuesta de a_arr :\n", a_arr.T)
print("Matriz transpuesta de a_arr :\n", np.transpose(a_arr))


a_arr :
 [[1 2 3]]
Matriz transpuesta de a_arr :
 [[1]
 [2]
 [3]]
Matriz transpuesta de a_arr :
 [[1]
 [2]
 [3]]


### Ejercicio 10

Crea una matriz `2x3` con números enteros aleatorios entre 0 y 100 y calcula su transpuesta.

Pista: puedes usar `np.random.randint` y luego `.T`.

In [ ]:
# TO DO
# 1) Genera una matriz aleatoria de forma (2, 3).
# 2) Calcula su transpuesta.
# 3) Imprime ambas matrices para comparar dimensiones.

In [135]:
matriz = np.random.randint(0, 101, size=(2, 3))
print(matriz)
print("Matriz transpuesta de a_arr :\n", matriz.T)
print("Matriz transpuesta de a_arr :\n", np.transpose(matriz))

[[31 98 33]
 [ 9 30 63]]
Matriz transpuesta de a_arr :
 [[31  9]
 [98 30]
 [33 63]]
Matriz transpuesta de a_arr :
 [[31  9]
 [98 30]
 [33 63]]


In [136]:
matriz = np.random.randint(0, 101, size=(2, 3))
print("Matriz original:\n", matriz)

transpuesta = matriz.T
print("Matriz transpuesta:\n", transpuesta)

Matriz original:
 [[45 32  8]
 [73 90  4]]
Matriz transpuesta:
 [[45 73]
 [32 90]
 [ 8  4]]


## 11. Union de matrices

Objetivo: combinar matrices por filas y columnas usando funciones de concatenacion.

In [137]:
a_arr = np.ones((3,3))
print("a_arr :\n", a_arr)

b_arr = np.zeros((3,3))
print("b_arr :\n", b_arr)

a_arr :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
b_arr :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [138]:
np.vstack((a_arr, b_arr))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [139]:
np.hstack((a_arr, b_arr))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [140]:
a_arr = np.array([10, 20, 30])
b_arr = np.array([40, 50, 60])
c_arr = np.array([70, 80, 90])

np.concatenate((a_arr, b_arr, c_arr))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [143]:

np.array((a_arr, b_arr, c_arr))

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [144]:
np.vstack((a_arr, b_arr, c_arr)) #  Use `np.vstack` directly

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [145]:
np.column_stack((a_arr, b_arr, c_arr)) # Use `np.hstack` directly

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

### Ejercicio 11

Construye el siguiente arreglo:

$$
\begin{bmatrix}
1 & 2 & 3 & 4 & 1 & 1 & 1 \\
5 & 6 & 7 & 8 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 2 & 4 & 6 \\
0 & 0 & 0 & 0 & 8 & 10 & 12 \\
1 & 1 & 1 & 1 & -1 & -1 & -1 \\
1 & 1 & 1 & 1 & -1 & -1 & -1
\end{bmatrix}
$$

Pista: crea bloques por separado y unelos con operaciones de concatenacion.

In [ ]:
# TO DO
# 1) Crea submatrices (bloques) con los valores solicitados.
# 2) Une los bloques por filas/columnas para formar la matriz final.
# 3) Verifica la forma final con .shape.

In [ ]:
a_1 = np.arange(1, 9).reshape((2, 4))
print("a_1 :\n", a_1)
a_2 = np.zeros((2, 4))
print("a_2 :\n", a_2)
a_3 = np.ones((2, 4))
print("a_3 :\n", a_3)

a_1 :
 [[1 2 3 4]
 [5 6 7 8]]
a_2 :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
a_3 :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 12.- Referencia a Objetos

In [149]:
a_arr = np.array([1, 2, 3, 4])
print("a_arr :", a_arr)

a_arr : [1 2 3 4]


In [150]:
ref_a_arr = a_arr
print("ref_a_arr :", ref_a_arr)

ref_a_arr : [1 2 3 4]


In [151]:
ref_a_arr[0] = 10
print("Después de modificar ref_a_arr[0] a 10:")
print("a_arr :", a_arr)
print("ref_a_arr :", ref_a_arr)

Después de modificar ref_a_arr[0] a 10:
a_arr : [10  2  3  4]
ref_a_arr : [10  2  3  4]


## 13.- Vista de Objetos

In [152]:
a_arr = np.array([10, 20, 30, 40])
print("a_arr :", a_arr)

a_arr : [10 20 30 40]


In [154]:
# Crear una vista del arreglo original
vista_a_arr = a_arr[:]
print("vista_a_arr :", vista_a_arr)

vista_a_arr : [10 20 30 40]


In [155]:
vista_a_arr[0] = 1000
print("Después de modificar vista_a_arr[0] a 1000:")
print("a_arr :", a_arr)
print("vista_a_arr :", vista_a_arr)

Después de modificar vista_a_arr[0] a 1000:
a_arr : [1000   20   30   40]
vista_a_arr : [1000   20   30   40]


## 14.- Copia de un objeto

In [158]:
a_arr = np.array([10, 20, 30, 40])
print("a_arr :", a_arr)

a_arr : [10 20 30 40]


In [159]:
# Crear una copia del arreglo original
cp_a_arr = a_arr.copy()
print("cp_a_arr :", cp_a_arr)

cp_a_arr : [10 20 30 40]


In [160]:
cp_a_arr[0] = 1000
print("Después de modificar cp_a_arr[0] a 1000:")
print("a_arr :", a_arr)
print("cp_a_arr :", cp_a_arr)

Después de modificar cp_a_arr[0] a 1000:
a_arr : [10 20 30 40]
cp_a_arr : [1000   20   30   40]


## 15.- Lectura de archivos

In [172]:
import numpy as np

# Lectura de datos desde un archivo de texto
data = np.loadtxt('dataset/delivery/entregas.txt', skiprows=1)
print(data)

[[  1. 656.   5.]
 [  2. 853.  14.]
 [  3. 646.   6.]
 [  4. 783.  11.]
 [  5. 610.   8.]
 [  6. 841.  10.]
 [  7. 785.   9.]
 [  8. 639.   9.]
 [  9. 762.  10.]
 [ 10. 762.   9.]
 [ 11. 862.   7.]
 [ 12. 679.   5.]
 [ 13. 835.  13.]
 [ 14. 607.   3.]
 [ 15. 665.   8.]
 [ 16. 647.   7.]
 [ 17. 685.  10.]
 [ 18. 720.   8.]
 [ 19. 652.   6.]
 [ 20. 828.  10.]]


In [173]:
# Lectura de datos desde un archivo de texto, seleccionando columnas específicas
data = np.loadtxt('dataset/delivery/entregas.txt', skiprows=1, usecols=(1,2))
print(data)

[[656.   5.]
 [853.  14.]
 [646.   6.]
 [783.  11.]
 [610.   8.]
 [841.  10.]
 [785.   9.]
 [639.   9.]
 [762.  10.]
 [762.   9.]
 [862.   7.]
 [679.   5.]
 [835.  13.]
 [607.   3.]
 [665.   8.]
 [647.   7.]
 [685.  10.]
 [720.   8.]
 [652.   6.]
 [828.  10.]]


In [174]:
## Lectura de archivo CSV con numpy
data = np.genfromtxt('dataset/delivery/entregas.csv', delimiter=';', skip_header=1)
print(data)

[[  1. 656.   5.]
 [  2. 853.  14.]
 [  3. 646.   6.]
 [  4. 783.  11.]
 [  5. 610.   8.]
 [  6. 841.  10.]
 [  7. 785.   9.]
 [  8. 639.   9.]
 [  9. 762.  10.]
 [ 10. 762.   9.]
 [ 11. 862.   7.]
 [ 12. 679.   5.]
 [ 13. 835.  13.]
 [ 14. 607.   3.]
 [ 15. 665.   8.]
 [ 16. 647.   7.]
 [ 17. 685.  10.]
 [ 18. 720.   8.]
 [ 19. 652.   6.]
 [ 20. 828.  10.]]


In [175]:
# Cargar archivo CSV con grenfromtxt
data = np.genfromtxt('dataset/panamericanos/medallero_Panamericanos_Lima2019.csv', delimiter=',', names=True, dtype=None)
print(data)

[( 1, 'Estados Unidos', 120, 88, 85, 293,  1, 'America del Norte')
 ( 2, 'Brasil',  55, 45, 71, 171,  2, 'America del Sur')
 ( 3, 'México',  37, 36, 63, 136,  4, 'America del Norte')
 ( 4, 'Canadá',  35, 64, 53, 152,  3, 'America del Norte')
 ( 5, 'Cuba',  33, 27, 38,  98,  6, 'America del Centro')
 ( 6, 'Argentina',  32, 35, 34, 101,  5, 'America del Sur')
 ( 7, 'Colombia',  28, 23, 33,  84,  7, 'America del Sur')
 ( 8, 'Chile',  13, 19, 18,  50,  8, 'America del Sur')
 ( 9, 'Perú',  11,  7, 21,  39, 11, 'America del Sur')
 (10, 'República Dominicana',  10, 13, 17,  40, 10, 'America del Centro')
 (11, 'Ecuador',  10,  7, 14,  31, 12, 'America del Sur')
 (12, 'Venezuela',   9, 15, 19,  43,  9, 'America del Sur')
 (13, 'Jamaica',   6,  6,  7,  19, 14, 'America del Centro')
 (14, 'Puerto Rico',   5,  5, 14,  24, 13, 'America del Centro')
 (15, 'El Salvador',   3,  0,  1,   4, 21, 'America del Centro')
 (16, 'Guatemala',   2,  9,  8,  19, 14, 'America del Centro')
 (17, 'Trinidad y Tobago

In [176]:
# Cargar archivo CSV con grenfromtxt
data = np.genfromtxt('dataset/panamericanos/medallero_Panamericanos_Lima2019.csv', delimiter=',', names=True, dtype=None, encoding='utf-8')
print(data)

[( 1, 'Estados Unidos', 120, 88, 85, 293,  1, 'America del Norte')
 ( 2, 'Brasil',  55, 45, 71, 171,  2, 'America del Sur')
 ( 3, 'México',  37, 36, 63, 136,  4, 'America del Norte')
 ( 4, 'Canadá',  35, 64, 53, 152,  3, 'America del Norte')
 ( 5, 'Cuba',  33, 27, 38,  98,  6, 'America del Centro')
 ( 6, 'Argentina',  32, 35, 34, 101,  5, 'America del Sur')
 ( 7, 'Colombia',  28, 23, 33,  84,  7, 'America del Sur')
 ( 8, 'Chile',  13, 19, 18,  50,  8, 'America del Sur')
 ( 9, 'Perú',  11,  7, 21,  39, 11, 'America del Sur')
 (10, 'República Dominicana',  10, 13, 17,  40, 10, 'America del Centro')
 (11, 'Ecuador',  10,  7, 14,  31, 12, 'America del Sur')
 (12, 'Venezuela',   9, 15, 19,  43,  9, 'America del Sur')
 (13, 'Jamaica',   6,  6,  7,  19, 14, 'America del Centro')
 (14, 'Puerto Rico',   5,  5, 14,  24, 13, 'America del Centro')
 (15, 'El Salvador',   3,  0,  1,   4, 21, 'America del Centro')
 (16, 'Guatemala',   2,  9,  8,  19, 14, 'America del Centro')
 (17, 'Trinidad y Tobago

In [177]:
data = np.fromfile('binario.bin', dtype=np.float64)
print(data)

[1.1 2.2 3.3 4.4 5.5]


In [178]:
data = np.fromfile('binario.bin', dtype=np.float64, count=3)
print(data)

[1.1 2.2 3.3]


## 16. Escritura de archivos

Objetivo: guardar resultados procesados en archivos para reutilizarlos en otros flujos de trabajo.

In [180]:

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 99]])
np.savetxt('salida.txt', data, fmt='%d', delimiter=',')


In [181]:
data = np.array([10, 20, 30])
np.save("data.npy", data)


data_loaded = np.load("data.npy")
print(data_loaded)


[10 20 30]
