In [148]:
'''
Modulo 2 : Estadistica y Visualizacion de Datos
Sesion : 01
Fecha : 25/10/2025
'''
print("Modulo 2 : Estadistica y Visualizacion de Datos")

Modulo 2 : Estadistica y Visualizacion de Datos


### 1.- Trabajando con listados

In [149]:
import numpy as np

nros = [ x for x in range(30)]
print(nros)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


In [150]:
np_nros = np.array(nros)
print(np_nros)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [151]:
print("np_nros.dtype :", np_nros.dtype)
print("np_nros.ndim :", np_nros.ndim)
print("np_nros.size :", np_nros.size)
print("np_nros.shape :", np_nros.shape)
print("np_nros.itemsize :", np_nros.itemsize)
print("np_nros.data :", np_nros.data)

np_nros.dtype : int64
np_nros.ndim : 1
np_nros.size : 30
np_nros.shape : (30,)
np_nros.itemsize : 8
np_nros.data : <memory at 0x10a912140>


### 2.- Trabajando con Arrays

In [152]:
nros = [
        [ x for x in range(10)],
        [ y for y in range(10)],
        [ z for z in range(10)]
    ]
#print(nros)
np_nros = np.array(nros)
print(np_nros)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [153]:
print("np_nros.dtype :", np_nros.dtype)
print("np_nros.ndim :", np_nros.ndim)
print("np_nros.size :", np_nros.size)
print("np_nros.shape :", np_nros.shape)
print("np_nros.itemsize :", np_nros.itemsize)
print("np_nros.data :", np_nros.data)

np_nros.dtype : int64
np_nros.ndim : 2
np_nros.size : 30
np_nros.shape : (3, 10)
np_nros.itemsize : 8
np_nros.data : <memory at 0x13a780520>


#### Ejercicio 1 : Crear un arreglo numpy que tenga 3 filas, 
- La 1ra fila tiene los numeros de 0,2,....,10 
- La 2da fila tiene los numeros : 1,3,5,...,11
- La 3ra fila tiene los numeros : 10, 30, 50 , ...., 110.

In [154]:
import numpy as np

fila1 = range(0, 11, 2)  
fila2 = range(1, 12, 2)  
fila3 = range(10, 111, 20)  
arreglo = np.array([fila1, fila2, fila3])
print("Arreglo resultante:")
print(arreglo)

Arreglo resultante:
[[  0   2   4   6   8  10]
 [  1   3   5   7   9  11]
 [ 10  30  50  70  90 110]]


### 2.- Creación de Arrays Numpy

In [155]:
np_z = np.zeros((3, 4))  # Arreglo de ceros de 3 filas y 4 columnas    
np_z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [156]:
np_o = np.ones((2, 5))  # Arreglo de unos de 2 filas y 5 columnas    
np_o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [157]:
np_nros = np.arange(30, 51)  # Arreglo con valores desde 10 hasta 50
np_nros

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50])

### 3.- Operaciones Básicas

In [158]:
# Como sumamos a una lista un valor escalar?
arr1 = range(4)
print("arr1 :", arr1)
#print("arr1 + 5 :", arr1 + 5) # Esto generará un error
print("arr1 + 5 :", [x + 5 for x in arr1])  # Suma 5 a cada elemento usando comprensión de listas

arr1 : range(0, 4)
arr1 + 5 : [5, 6, 7, 8]


In [159]:
# SUMA Y MULTIPLICACION CON NUMPY
np_arr1 = np.arange(4)
print("np_arr1 :", np_arr1)
print("Suma 5 a cada elemento de np_arr1 :",np_arr1  + 5 )  # Suma 5 a cada elemento
print("Multiplica por 5 a cada elemento de np_arr1 :",np_arr1  * 5 )  # Multiplicar por 5 a cada elemento

np_arr1 : [0 1 2 3]
Suma 5 a cada elemento de np_arr1 : [5 6 7 8]
Multiplica por 5 a cada elemento de np_arr1 : [ 0  5 10 15]


In [160]:
# RESTA Y DIVISION CON NUMPY
np_arr1 = np.arange(4,8)
print("np_arr1 :", np_arr1)
print("Resta 5 a cada elemento de np_arr1 :",np_arr1  - 5 )  # Resta 5 a cada elemento
print("Divide 5 a cada elemento de np_arr1 :",np_arr1  / 5 )  # Divide 5 a cada elemento

np_arr1 : [4 5 6 7]
Resta 5 a cada elemento de np_arr1 : [-1  0  1  2]
Divide 5 a cada elemento de np_arr1 : [0.8 1.  1.2 1.4]


### Ejercicio 2 : 
Crear un arreglo numpy con los números 10,30,50,70,...,130 luego realizar las siguiente operaciones
- Dividir entre 10 a todos los elementos
- Restar 3 al resultado anterior
- Sumar 1 a resultado anterior
- Mutiplicar por -1 al resultado anterior y mostrarlo

In [161]:
np_arr_original = np.arange(10,150,20)

np_arr2 = np_arr_original.copy()  
print(np_arr2)

np_arr2 = np_arr2 / 10
print("np_arr2 suma : ", np_arr2)

np_arr2 = np_arr2 -3
print("np_arr2 menos 3 : ", np_arr2)

print("np_arr_original : ", np_arr_original)

[ 10  30  50  70  90 110 130]
np_arr2 suma :  [ 1.  3.  5.  7.  9. 11. 13.]
np_arr2 menos 3 :  [-2.  0.  2.  4.  6.  8. 10.]
np_arr_original :  [ 10  30  50  70  90 110 130]


In [162]:
# Operaciones entre arreglos
np_arr1 = np.arange(4)      
np_arr2 = np.arange(4,8)

print("np_arr1 :", np_arr1)
print("np_arr2 :", np_arr2)    
print("Suma de np_arr1 + np_arr2 :", np_arr1 + np_arr2)
print("Resta de np_arr1 - np_arr2 :", np_arr1 - np_arr2)
print("Multiplicacion de np_arr1 * np_arr2 :", np_arr1 * np_arr2)
print("Division de np_arr1 / np_arr2 :", np_arr1 / np_arr2)


np_arr1 : [0 1 2 3]
np_arr2 : [4 5 6 7]
Suma de np_arr1 + np_arr2 : [ 4  6  8 10]
Resta de np_arr1 - np_arr2 : [-4 -4 -4 -4]
Multiplicacion de np_arr1 * np_arr2 : [ 0  5 12 21]
Division de np_arr1 / np_arr2 : [0.         0.2        0.33333333 0.42857143]


In [163]:
(np_arr1 / np_arr2)*np_arr2

array([0., 1., 2., 3.])

### Ejercicio 3 :
se tiene los siguiente arreglos
- [0,1,0]
- [1,0,0]
- [0,0,1]

Se pide calcular la suma y el producto de los arreglos

In [164]:
import numpy as np

array1 = np.array([0, 1, 0])
array2 = np.array([1, 0, 0])
array3 = np.array([0, 0, 1])

suma = array1 + array2 + array3
producto = array1*array2*array3

print("suma: ", suma)
print("producto: ", producto)

suma:  [1 1 1]
producto:  [0 0 0]


### 4.- Producto de matrices

<img src="imagenes/producto_punto.jpg" width="400" />

In [165]:
a_arr = np.arange(4)      
b_arr = np.arange(4,8)

print("a_arr :", a_arr)
print("b_arr :", b_arr)
print(sum(a_arr * b_arr))
print(np.dot(a_arr, b_arr))  # Producto punto de a_arr y b_arr
print(np.dot(b_arr, a_arr))  # Producto punto de b_arr y a_arr


a_arr : [0 1 2 3]
b_arr : [4 5 6 7]
38
38
38


In [166]:
a_arr = np.array([[1, 2], [3, 4]])
b_arr = np.array([[5, 6], [7, 8]])      

print("a_arr :\n", a_arr)
print("b_arr :\n", b_arr)

c_arr = a_arr.dot(b_arr)
print("Producto de matrices a_arr . b_arr :\n", c_arr)  

c_arr = np.dot(a_arr,b_arr)
print("Producto de matrices a_arr . b_arr :\n", c_arr)  


a_arr :
 [[1 2]
 [3 4]]
b_arr :
 [[5 6]
 [7 8]]
Producto de matrices a_arr . b_arr :
 [[19 22]
 [43 50]]
Producto de matrices a_arr . b_arr :
 [[19 22]
 [43 50]]


## Ejercicio 4
Dados los vectores:

- A = [3, 4]
- B = [2, 5]

Calcular:

- El producto punto A · B
- Las magnitudes |A| y |B|

In [167]:
# Cambiar la forma de un arreglo
np_arr = np.arange(12)  # Arreglo con valores del 0 al 11
print("Arreglo original:")
print(np_arr)
np_arr_reshaped = np_arr.reshape((3, 4))  # Cambiar la forma a 3 filas y 4 columnas
print("Arreglo con nueva forma (3x4):")
print(np_arr_reshaped)

Arreglo original:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Arreglo con nueva forma (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 5.- Funciones utilitarias 

In [168]:
a_arr = np.arange(4,8)
print("a_arr :", a_arr)

# Elevar a una potencia cada elemento
print("a_arr elevado al cubo :", np.power(a_arr, 3))

# Sumar todos los elementos del arreglo
print("Suma de todos los elementos de a_arr :", np.sum(a_arr))

# Obtener el valor minimo de todos los elementos
print("Valor minimo de a_arr :", np.min(a_arr))

# Obtener el valor maximo de todos los elementos
print("Valor maximo de a_arr :", np.max(a_arr)) 

# Calcular la media de los elementos
print("Media de los elementos de a_arr :", np.mean(a_arr))

# Calcular la desviacion estandar de los elementos
print("Desviacion estandar de los elementos de a_arr :", np.std(a_arr))

# Calcular la varianza de los elementos
print("Varianza de los elementos de a_arr :", np.var(a_arr))    

# Calcular la raiz cuadrada de cada elemento
print("Raiz cuadrada de cada elemento de a_arr :", np.sqrt(a_arr))  


a_arr : [4 5 6 7]
a_arr elevado al cubo : [ 64 125 216 343]
Suma de todos los elementos de a_arr : 22
Valor minimo de a_arr : 4
Valor maximo de a_arr : 7
Media de los elementos de a_arr : 5.5
Desviacion estandar de los elementos de a_arr : 1.118033988749895
Varianza de los elementos de a_arr : 1.25
Raiz cuadrada de cada elemento de a_arr : [2.         2.23606798 2.44948974 2.64575131]


## Ejercicio 6

Dada las notas de 2 estudiantes en 5 cursos

- estudiante_A = np.array([18, 14, 20, 10, 15])
- estudiante_B = np.array([17, 16, 17, 14, 18])

Calcular una tabla comparativa de la nota promedio , miníma y máxima de los estudiantes



In [169]:
estudiante_A = np.array([18, 14, 20, 10, 15])
estudiante_B = np.array([17, 16, 17, 14, 18])

print("Media de estudiante_A :", np.mean(estudiante_A))
print("Media de estudiante_B :", np.mean(estudiante_B))
print("Minimo de estudiante_A :", np.min(estudiante_A))
print("Minimo de estudiante_B :", np.min(estudiante_B))
print("Maximo de estudiante_A :", np.max(estudiante_A))
print("Maximo de estudiante_B :", np.max(estudiante_B))

Media de estudiante_A : 15.4
Media de estudiante_B : 16.4
Minimo de estudiante_A : 10
Minimo de estudiante_B : 14
Maximo de estudiante_A : 20
Maximo de estudiante_B : 18


## 7.- Iteracciones por columnas y filas

In [170]:
a_arr = np.arange(0,12).reshape((3,4))
print("a_arr :\n", a_arr)

# Sumas

# Procesar por columnas
col_proc = np.apply_along_axis(np.sum, axis=0, arr=a_arr)
print("Suma por columnas :", col_proc)

# Procesar por filas
filas_proc = np.apply_along_axis(np.sum, axis=1, arr=a_arr)
print("Suma por filas :", filas_proc)

# Promedios

# Procesar por columnas
col_proc = np.apply_along_axis(np.mean, axis=0, arr=a_arr)
print("Promedio por columnas :", col_proc)

# Procesar por filas
filas_proc = np.apply_along_axis(np.mean, axis=1, arr=a_arr)
print("Promedio por filas :", filas_proc)


a_arr :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Suma por columnas : [12 15 18 21]
Suma por filas : [ 6 22 38]
Promedio por columnas : [4. 5. 6. 7.]
Promedio por filas : [1.5 5.5 9.5]


In [171]:
def potencia(x):
    return x ** 2

a_arr = np.arange(0,12).reshape((3,4))
print("a_arr :\n", a_arr)


b_arr =  np.apply_along_axis(potencia, axis=1, arr=a_arr)
print("b_arr :\n", b_arr)

a_arr :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b_arr :
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


### Ejercicio 7
Dado el PBI de Chile, Perú y Colombia del año 2020 al 2026, debera calcular

- El promedio del PBI de los 3 paises por año
- El promedio del PBI de cada pais independiente del 2020 al 2026

Perú -> 209,984	229,832	248,204	271,780	294,675	318,480	326,608	
Chile -> 254,060	315,411	301,270	335,627	330,210	347,174	363,299	
Colombia -> 270,348	318,525	345,632	366,292	418,818	438,121	462,251

# Crear arreglos para cada país (sin considerar nombres)

- peru = np.array([209984, 229832, 248204, 271780, 294675, 318480, 326608])
- chile = np.array([254060, 315411, 301270, 335627, 330210, 347174, 363299])
- colombia = np.array([270348, 318525, 345632, 366292, 418818, 438121, 462251])


## 8.- Condiciones y expresiones booleanas

In [1]:
a_arr = np.arange(0,12).reshape((3,4))
print("a_arr :\n", a_arr)

# Condiciones y expresio
print(a_arr > 5)

NameError: name 'np' is not defined

In [ ]:
a_arr[a_arr > 5]

array([ 6,  7,  8,  9, 10, 11])

## Ejercicio 8

Dada las notas de 2 estudiantes

- estudiante_A = np.array([18, 14, 20, 10, 15])
- estudiante_B = np.array([17, 16, 17, 14, 18])

Se pide calcular el promedio de las notas, y obtener todas las notas que son mayores al promedio general



In [ ]:
notas = np.array(
    [
        [18, 14, 20, 10, 15],
        [17, 16, 17, 14, 18]
    ])

promedio_general = np.mean(notas)
print("Promedio general de las notas :", promedio_general)

# TO DO: Completar el filtro para obtener las notas mayores al promedio general



Promedio general de las notas : 15.9


## 9.- Cambio de dimension de un arreglo 

In [ ]:
# Creacion de un arreglo aleatorio, de 3 x4 
a_arr = np.random.random((3,4))
print("a_arr :\n", a_arr)

# Cambio de dimension de un arreglo
print(a_arr.ravel())

a_arr :
 [[0.21047795 0.98239905 0.55997683 0.51054514]
 [0.26150568 0.92804576 0.71099227 0.00616372]
 [0.77093502 0.96675644 0.94019323 0.32965035]]
[0.21047795 0.98239905 0.55997683 0.51054514 0.26150568 0.92804576
 0.71099227 0.00616372 0.77093502 0.96675644 0.94019323 0.32965035]


## 10.- Transpuesta de matrices

In [ ]:
# Creacion de un arreglo aleatorio, de 1x2 
a_arr = np.random.random((1,2))
print("a_arr :\n", a_arr)

# Generacion de matriz transpuesta
print("Matriz transpuesta de a_arr :\n", a_arr.T)
print("Matriz transpuesta de a_arr :\n", np.transpose(a_arr))


a_arr :
 [[0.52050996 0.62595079]]
Matriz transpuesta de a_arr :
 [[0.52050996]
 [0.62595079]]
Matriz transpuesta de a_arr :
 [[0.52050996]
 [0.62595079]]


## Ejercicio 10 , 
Crear numero enteros aleatorio entre 0 a 100 en una matriz de 2x3 , y hallar su matriz transpuesta

## 11.-  Unión de matrices


In [ ]:
a_arr = np.ones((3,3))
print("a_arr :\n", a_arr)

b_arr = np.zeros((3,3))
print("b_arr :\n", b_arr)

a_arr :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
b_arr :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
np.vstack((a_arr, b_arr))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.hstack((a_arr, b_arr))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [ ]:
a_arr = np.array([10, 20, 30])
b_arr = np.array([40, 50, 60])
c_arr = np.array([70, 80, 90])

np.concatenate((a_arr, b_arr, c_arr))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.row_stack((a_arr, b_arr, c_arr)) #  Use `np.vstack` directly

/var/folders/c7/p02yvsh9697_g6yclqsn8p440000gn/T/ipykernel_94502/3952489378.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a_arr, b_arr, c_arr)) #  Use `np.vstack` directly


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
np.column_stack((a_arr, b_arr, c_arr)) # Use `np.hstack` directly

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

## Ejercicio 11 :
Crear el siguiente arreglo

$$
\begin{bmatrix}
1 & 2 & 3 & 4 & 1 & 1 & 1 \\
5 & 6 & 7 & 8 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 2 & 4 & 6 \\
0 & 0 & 0 & 0 & 8 & 10 & 12 \\
1 & 1 & 1 & 1 & -1 & -1 & -1 \\
1 & 1 & 1 & 1 & -1 & -1 & -1
\end{bmatrix}
$$


In [ ]:
part1 = np.arange(1,9).reshape(2,4)

part2 = np.ones((2,3))

part3 = np.zeros((2,4))

part4 = np.arange(2,13,2).reshape(2,3)

part5 = np.ones((2,4))

part6 = np.ones((2,3))*-1

f1_f2 = np.hstack((part1, part2))
f3_f4 = np.hstack((part3, part4))
f5_f6 = np.hstack((part5, part6))

final_arr = np.vstack((f1_f2, f3_f4, f5_f6))
print("final_arr :\n", final_arr)

final_arr :
 [[ 1.  2.  3.  4.  1.  1.  1.]
 [ 5.  6.  7.  8.  1.  1.  1.]
 [ 0.  0.  0.  0.  2.  4.  6.]
 [ 0.  0.  0.  0.  8. 10. 12.]
 [ 1.  1.  1.  1. -1. -1. -1.]
 [ 1.  1.  1.  1. -1. -1. -1.]]


## 12.- Referencia a Objetos

In [ ]:
a_arr = np.array([1, 2, 3, 4])
print("a_arr :", a_arr)

a_arr : [1 2 3 4]


In [ ]:
ref_a_arr = a_arr
print("ref_a_arr :", ref_a_arr)

ref_a_arr : [1 2 3 4]


In [ ]:
ref_a_arr[0] = 10
print("Después de modificar ref_a_arr[0] a 10:")
print("a_arr :", a_arr)
print("ref_a_arr :", ref_a_arr)

Después de modificar ref_a_arr[0] a 10:
a_arr : [10  2  3  4]
ref_a_arr : [10  2  3  4]


## 13.- Vista de Objetos

In [ ]:
a_arr = np.array([10, 20, 30, 40])
print("a_arr :", a_arr)

a_arr : [10 20 30 40]


In [ ]:
vista_a_arr = a_arr[0:4]
print("vista_a_arr :", vista_a_arr)

vista_a_arr : [10 20 30 40]


In [ ]:
vista_a_arr[0] = 1000
print("Después de modificar vista_a_arr[0] a 1000:")
print("a_arr :", a_arr)
print("vista_a_arr :", vista_a_arr)

Después de modificar vista_a_arr[0] a 1000:
a_arr : [1000   20   30   40]
vista_a_arr : [1000   20   30   40]


## 14.- Copia de un objeto

In [ ]:
a_arr = np.array([10, 20, 30, 40])
print("a_arr :", a_arr)

a_arr : [10 20 30 40]


In [ ]:
vista_a_arr = a_arr.copy()
print("vista_a_arr :", vista_a_arr)

vista_a_arr : [10 20 30 40]


In [ ]:
vista_a_arr[0] = 1000
print("Después de modificar vista_a_arr[0] a 1000:")
print("a_arr :", a_arr)
print("vista_a_arr :", vista_a_arr)

Después de modificar vista_a_arr[0] a 1000:
a_arr : [10 20 30 40]
vista_a_arr : [1000   20   30   40]


## Lectura de archivos

In [ ]:
import numpy as np

# Lectura de datos desde un archivo de texto
data = np.loadtxt('entregas.txt', skiprows=1)
print(data)

[[  1. 656.   5.]
 [  2. 853.  14.]
 [  3. 646.   6.]
 [  4. 783.  11.]
 [  5. 610.   8.]
 [  6. 841.  10.]
 [  7. 785.   9.]
 [  8. 639.   9.]
 [  9. 762.  10.]
 [ 10. 762.   9.]
 [ 11. 862.   7.]
 [ 12. 679.   5.]
 [ 13. 835.  13.]
 [ 14. 607.   3.]
 [ 15. 665.   8.]
 [ 16. 647.   7.]
 [ 17. 685.  10.]
 [ 18. 720.   8.]
 [ 19. 652.   6.]
 [ 20. 828.  10.]]


In [ ]:
# Lectura de datos desde un archivo de texto, seleccionando columnas específicas
data = np.loadtxt('entregas.txt', skiprows=1, usecols=(0,1))
print(data)

[[  1. 656.]
 [  2. 853.]
 [  3. 646.]
 [  4. 783.]
 [  5. 610.]
 [  6. 841.]
 [  7. 785.]
 [  8. 639.]
 [  9. 762.]
 [ 10. 762.]
 [ 11. 862.]
 [ 12. 679.]
 [ 13. 835.]
 [ 14. 607.]
 [ 15. 665.]
 [ 16. 647.]
 [ 17. 685.]
 [ 18. 720.]
 [ 19. 652.]
 [ 20. 828.]]
